### PR TITLE
Add wind data to BD (Bangladesh)

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

The source was recently updated with wind data and the table layout changed so the parser is currently failing.

## Description

Adds wind data and adjust the table parsing to adjust for the alteration in the source layout.

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Review by unitrium — APPROVED** [review]
Thanks for fixing it ! Will deploy it tomorrow :)

**Comment by VIKTORVAV99** [comment]
Can you run a backfill as well?

**Comment by unitrium** [comment]
I ran a refetch, we will start a big flowtracing later with the changes from India as well.

**Comment by VIKTORVAV99** [comment]
> I ran a refetch, we will start a big flowtracing later with the changes from India as well.

There should be data available from early 2015 if needed.

**Pull request merged**
