### PR TITLE
fix(options requests): Fix OPTIONS request for state

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

Same as for feature flags, every time we are fetching a state we create 2 requests, one OPTIONS request that can't be cached and one GET request that we are able to cache. This increases server load more than needed as these are not authenticated requests.

## Description

Removes the authentication headers from state requests to prevent OPTIONS requests.

### Double check

- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@tonypls would you be comfortable merging this without us figuring out #6697?

**Comment by tonypls** [comment]
> @tonypls would you be comfortable merging this without us figuring out #6697?

Yeah sound good! I'm a bit worried that it's going to be hard to quickly identify regressions after the spike in error rate we saw on deployment yesterday. [Issue here](https://linear.app/electricitymaps/issue/AVO-233/improve-how-we-handle-distributing-web-app-updates) 

Perhaps we can use this change to do a small deployment and see if we can gain any more insight into the cause of the increased error rate.

**Comment by VIKTORVAV99** [comment]
> > @tonypls would you be comfortable merging this without us figuring out #6697?
> 
> 
> 
> Yeah sound good! I'm a bit worried that it's going to be hard to quickly identify regressions after the spike in error rate we saw on deployment yesterday. [Issue here](https://linear.app/electricitymaps/issue/AVO-233/improve-how-we-handle-distributing-web-app-updates) 
> 
> 
> 
> Perhaps we can use this change to do a small deployment and see if we can gain any more insight into the cause of the increased error rate.

Hmm yeah that sounds good, and I'd be happy to pick up the service worker parts again.

I know we were worried about the ability to roll back but I really don't think that is an issue or at least not big enough to be a blocker for it.

**Comment by tonypls** [comment]
> > > @tonypls would you be comfortable merging this without us figuring out #6697?
> > 
> > 
> > Yeah sound good! I'm a bit worried that it's going to be hard to quickly identify regressions after the spike in error rate we saw on deployment yesterday. [Issue here](https://linear.app/electricitymaps/issue/AVO-233/improve-how-we-handle-distributing-web-app-updates)
> > Perhaps we can use this change to do a small deployment and see if we can gain any more insight into the cause of the increased error rate.
> 
> Hmm yeah that sounds good, and I'd be happy to pick up the service worker parts again.
> 
> I know we were worried about the ability to roll back but I really don't think that is an issue or at least not big enough to be a blocker for it.


That would be awesome if you could prioritize app delivery, we get lots of errors after trying to read the client_version. I'm not sure service worker is going to solve this so feel free to re-work this approach if there's a better way to handle it. 

Now the rewrite is complete I think there's less concern about the ability to rollback (we did think by pointing to the instance of the old app I believe).

**Review by tonypls — APPROVED** [review]
LGTM

**Comment by VIKTORVAV99** [comment]
> > > > @tonypls would you be comfortable merging this without us figuring out #6697?
> > > 
> > > 
> > > Yeah sound good! I'm a bit worried that it's going to be hard to quickly identify regressions after the spike in error rate we saw on deployment yesterday. [Issue here](https://linear.app/electricitymaps/issue/AVO-233/improve-how-we-handle-distributing-web-app-updates)
> > > Perhaps we can use this change to do a small deployment and see if we can gain any more insight into the cause of the increased error rate.
> > 
> > 
> > Hmm yeah that sounds good, and I'd be happy to pick up the service worker parts again.
> > I know we were worried about the ability to roll back but I really don't think that is an issue or at least not big enough to be a blocker for it.
> 
> That would be awesome if you could prioritize app delivery, we get lots of errors after trying to read the client_version. I'm not sure service worker is going to solve this so feel free to re-work this approach if there's a better way to handle it.
> 
> Now the rewrite is complete I think there's less concern about the ability to rollback (we did think by pointing to the instance of the old app I believe).

When we are using a service worker I don't think we will need that part at all as it will have it's own list of assets with hashes and use that to check if there is a new version of the files in question using.

**Pull request merged**
