### PR TITLE
Update DATA_SOURCES.md

### PR DESCRIPTION
**Pull request by gadakast**
New sources, except for France

## Description
Sources for my capacity updates. NB: Belgium’s nuclear capacity is yet to be updated on IAEA’s website, since the change happened the day before my submit.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@gadakast there seems to be a conflict in the `DATA_SOURCES.md` file. If you can resolve that I can merge both of the PRs together.

**Comment by gadakast** [comment]
@VIKTORVAV99 Can you please clarify what sources seem to be in conflict? Does it have to do with the ‘Other’ source for peninsular Spain and Canary Islands?

**Comment by jarek** [comment]
I merged these changes into #4596 so that both the capacity changes and the corresponding source updates are in one pull request

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 Can you please clarify what sources seem to be in conflict? Does it have to do with the ‘Other’ source for peninsular Spain and Canary Islands?

jarek took care of it and moved your changes to the other PR, so everything is good to go now. I'll just do a final check after my uni class but there shouldn't be any more issues now.

**Pull request closed without merging**
