### PR TITLE
Rename BreakdownChart to OriginChart

### PR DESCRIPTION
**Pull request by cadeban**
## Description
Rename BreakdownChart to OriginChart.
BarBreakdownChart and BreakdownChart are very similarly named and the naming convention can cause confusion.

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Anything blocking this?
Would be nice to just get it merged 🙂

**Comment by cadeban** [comment]
The only thing missing is alignment!

**Review by VIKTORVAV99 — APPROVED** [review]
Consider us aligned!

**Comment by cadeban** [comment]
@tonypls @silkeholmebonnen Does this change work for y'all too?

**Review by silkeholmebonnen — APPROVED** [review]
LGTM!

**Comment by VIKTORVAV99** [comment]
@tonypls do you have any objections?

**Comment by tonypls** [comment]
!objections

**Comment by VIKTORVAV99** [comment]
Then let's merge this! 🥳

**Pull request merged**
