### PR TITLE
Update US-SW-PNM Coal Capacity

### PR DESCRIPTION
**Pull request by brandongalbraith**
Intent: Update [US-SW-PNM](https://app.electricitymaps.com/zone/US-SW-PNM?wind=false&solar=false) coal capacity based on San Juan Generation Station closure.

News report citation: [Albuquerque Journal: San Juan Generating Station to close this week (September 2022)](https://web.archive.org/web/20220928012000/https://www.abqjournal.com/2535435/san-juan-coal-plant-to-close-this-week.html)

Wikipedia page: https://en.wikipedia.org/wiki/San_Juan_Generating_Station

Planned retirement this month indicated in US EIA's EIA 860M for August 2022: https://web.archive.org/web/20220928013504/https://www.eia.gov/electricity/data/eia860m/archive/xls/august_generator2022.xlsx (Entity ID 15473, Plant ID 2451):

```
15473 | Public Service   Co of NM | 2451 | San Juan | Map | Map | NM | San Juan | PNM | Electric   Utility | 4 |   | 555.0 | 507.0 | 507.0 | Conventional   Steam Coal | RC | ST | 4 | 1982 | 9 | 2022 | (OP) Operating |   |   |   |   |   |   |   |   | 36.800600 | -108.438600
```

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
One less coal plant in the world, nice! 🎉

Everything looks good here so I'll approve and merge this as soon as you confirm it's closed down.

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 how long does it take for EM's ML models to update after capacity changes? If you review the estimated generation mix for this zone compared to actual delayed backfill, it appears coal generation estimates are inaccurate.

I actually have no idea about that as I don't have any access to that data due to not working for Electricity Maps. But perhaps you can shed some light about it @pierresegonne?

**Comment by pierresegonne** [comment]
> how long does it take for EM's ML models to update after capacity changes?

What you see is not influenced by installed capacity. https://github.com/electricitymaps/electricitymaps-contrib/wiki/Time-Slicer-Average Explains how we compute these estimates. This explains that the estimations overestimate coal production if historically, coal capacity was higher.

**Pull request merged**
