### PR TITLE
chore(workflows): try get the review bot working again

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
Codium PR agent stopped working

## Description

This PR brings the workflow config for codiums PR-agent closer to their defaults to raise it from the dead

### CODE REVIEW

**Comment by tonypls** [comment]
This might need to be merged before it starts working 🤷

**Review by VIKTORVAV99 — APPROVED** [review]
Changes look good and I think you are right in that it might need to run on "master" before it's working again so let's merge it and try.

**Pull request merged**
