### PR TITLE
refactor(web): add all trackevents strings to trackevent enum

### PR DESCRIPTION
**Pull request by silkeholmebonnen**
## Issue

[AVO-243](https://linear.app/electricitymaps/issue/AVO-243/add-existing-trackevents-to-enum)

## Description

This PR adds all the trackevent strings to an enum.

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — DISMISSED** [review]
LGTM! 🎉

**Comment by VIKTORVAV99** [comment]
I just saw that Tony mentioned that the function should be updated to only accept enum types. Do you mind doing that as well?

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Review by tonypls — APPROVED** [review]
Wahoo! LGTM!

**Pull request merged**
