### PR TITLE
Update US balancing authority naming

### LINKED ISSUE #5837: How should we name balancing authorities in USA? Feedback needed! 🙏
I'd like to get some feedback on how people would prefer the balancing authorities in US to be named.

Currently we're going with the full title on the app (e.g. California Independent System Operator) instead of the shorter California ISO (what they use on [their own website](http://www.caiso.com/about/Pages/News/default.aspx)) or even shorter CAISO.

Same with ERCOT vs Electric Reliability Council of Texas, and so on.

### Where we need your help

Since the internal team is either European or deeply involved in the energy sector, we're lacking an understanding of how everyday citizens in the US uses these names. How does the media use the names?

The current titles are often too long to be displayed in the app, so it would be nice if we could generally use the shorter names and maybe add the full title in a tooltip - but we don't want to make that move before hearing from you :)

### PR DESCRIPTION
**Pull request by madsnedergaard**
## Issue

Closes #5837, follow-up to #6498

## Description

This updates a lot of `zoneName` to remove "Inc" and similar, as well as adding a bunch of `displayName` properties with nicer names.

**This should only be merged after #6498 has been released and tested!**

### CODE REVIEW

**Comment by madsnedergaard** [comment]
This is good to go now, ERCOT looks fine :)
https://app.electricitymaps.com/zone/US-TEX-ERCO

**Review by VIKTORVAV99 — APPROVED** [review]
Question here, do we want to remove the translations from the other languages or just leave them for now?

Otherwise it looks good to me!

**Comment by madsnedergaard** [comment]
I'd say let's get this merged now, and then at some point in the future we should do a more thorough cleaning up of all translation files 😅

**Comment by VIKTORVAV99** [comment]
> I'd say let's get this merged now, and then at some point in the future we should do a more thorough cleaning up of all translation files 😅 

I have a plan for that! Not enough to be its own project just yet but I'll restructure a few things at one point so we can use already available tooling.

**Pull request merged**
