### PR TITLE
[WIP] Removes old zones for India (IN) 🇮🇳 

### PR DESCRIPTION
**Pull request by madsnedergaard**
## Description

Replaces #4993 with a more thorough removal of old zones for India, based on the updated script in #5491.

This removes config, exchanges, translations and more for the following list of zones:

- IN-DL
- IN-HP
- IN-KA
- IN-MH
- IN-PB
- IN-UP
- IN-UT
- IN-AR
- IN-AS
- IN-BR
- IN-CT
- IN-DN
- IN-GA
- IN-GJ
- IN-HR
- IN-JH
- IN-JK
- IN-KL
- IN-ML
- IN-MN
- IN-MP
- IN-MZ
- IN-NL
- IN-OR
- IN-PY
- IN-RJ
- IN-SK
- IN-TN
- IN-TR
- IN-WB

### CODE REVIEW

**Comment by pierresegonne** [comment]
I think there is a risk that this is going to block the contrib release pipeline. 

Let's test thoroughly on the internal side before merging

**Comment by madsnedergaard** [comment]
> I think there is a risk that this is going to block the contrib release pipeline.
> 
> Let's test thoroughly on the internal side before merging

Yes, I'll make a branch on the backend that references this branch, so we don't have to merge it in order to test :)

**Comment by pierresegonne** [comment]
Should we pick this up on the next slack week?

**Comment by madsnedergaard** [comment]
Yup! :)

**Comment by madsnedergaard** [comment]
Status here is that we need to clean up usage of old zones everywhere on the backend before we can merge this.

**Comment by madsnedergaard** [comment]
TODO: Split this into smaller PRs!

**Comment by madsnedergaard** [comment]
Closing this in favor of smaller PRs

**Pull request closed without merging**
