### PR TITLE
restore SE-SE3 SE-SE4 border change

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
Looks like this change got reverted in the merge conflict we had.
~~I'll run the update world script once #4786 is merged to avoid further conflicts.~~ Done!

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
After this is merged we should publish a new mobile app build to get the gemoetry changes into the apps.

**Comment by madsnedergaard** [comment]
> After this is merged, we should publish a new mobile app build to get the geometry changes into the apps.

Good point, will do!

**Comment by madsnedergaard** [comment]
Just noticed the exchange arrow positioning between these two zones is wrong on production, should we fix this here? :)

**Comment by VIKTORVAV99** [comment]
> Just noticed the exchange arrow positioning between these two zones is wrong on production, should we fix this here? :) Screenshot 2022-11-23 at 10 47 27

It's the border that's wrong! 😅

In #4754 I moved both the border and exchange arrow but then there was a merge conflict in another PR and the geometry changes where lost, this PR restores that, so the border is under the arrow again.

**Review by Kongkille — APPROVED** [review]

**Comment by VIKTORVAV99** [comment]
@madsnedergaard should be good to go for a new mobile build now.

**Pull request merged**
