### PR TITLE
Updated PT Capacities

### PR DESCRIPTION
**Pull request by Musketeiro**
Updated capacities per official numbers from REN.

### CODE REVIEW

**Review by VIKTORVAV99 — COMMENTED** [review]
Thanks for making this PR!

Currently REN is marked in DATA_SOURCES.md as the source for biomass, hydro, solar and wind only. Could you update that file to mention that it's used for gas as well?

**Comment by Musketeiro** [comment]
Done. I also changed the link so it displays the English version.
@VIKTORVAV99

**Comment by VIKTORVAV99** [comment]
> Done. I also changed the link so it displays the English version. @VIKTORVAV99

Thanks! I'll approve it and merge it right away!

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
