### PR TITLE
Add historical prices

### PR DESCRIPTION
**Pull request by corradio**
## Issue
Fixes https://github.com/electricitymaps/electricitymaps-contrib/issues/4424

image

### CODE REVIEW

**Review by madsnedergaard — COMMENTED** [review]
LGTM, leaving approval for @Kongkille as I've forgotten too much context around this 🙃

**Comment by VIKTORVAV99** [comment]
Nice, will be awesome to visualize the impact the current energy "crisis" have had.

Next up aggregated prices? We should be able to use the same kind of model discussed in #4424 with some tweaks.

**Comment by corradio** [comment]
> Nice, will be awesome to visualize the impact the current energy "crisis" have had.
> 
> Next up aggregated prices? We should be able to use the same kind of model discussed in #4424 with some tweaks.

These **are** the historical prices!

**Review by Kongkille — APPROVED** [review]
Excellent (;

**Comment by VIKTORVAV99** [comment]
Just realized this, we don't explain the method anywhere (in the frontend) right?
Perhaps we should add a note about it in the FAQ?

**Pull request merged**
