### PR TITLE
chore: ranking panel translations cleanup

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

I forgot to do this in the ranking panel PR.

## Description
Cleans up the keys so the correct translations are used.

### Double check
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by Alportan** [comment]
So basically this is just using a `ranking-panel` section for the translation files instead of the `left-panel`? 🙌

**Comment by VIKTORVAV99** [comment]
> So basically this is just using a `ranking-panel` section for the translation files instead of the `left-panel`? 🙌

Yeah, the left panel is still there as it contains these in English:
```json
  "left-panel": {
    "get-data": "See our commercial API offerings",
    "applied-methodologies": {
      "title": "Applied methodologies",
      "estimations": "Electricity Maps - Estimations",
      "flowtracing": "Electricity Maps - Flow-tracing",
      "carbonintensity": "Electricity Maps - Carbon intensity"
    }
  }
```
But I'll try and move those out to their own fields where it makes sense in another PR.

The original changes have already been made for English but I forgot to change all the other languages 🫠

**Comment by Alportan** [comment]
> > So basically this is just using a `ranking-panel` section for the translation files instead of the `left-panel`? 🙌
> 
> Yeah, the left panel is still there as it contains these in English:
> 
> ```json
>   "left-panel": {
>     "get-data": "See our commercial API offerings",
>     "applied-methodologies": {
>       "title": "Applied methodologies",
>       "estimations": "Electricity Maps - Estimations",
>       "flowtracing": "Electricity Maps - Flow-tracing",
>       "carbonintensity": "Electricity Maps - Carbon intensity"
>     }
>   }
> ```
> 
> But I'll try and move those out to their own fields where it makes sense in another PR.
> 
> The original changes have already been made for English but I forgot to change all the other languages 🫠

Gotcha! Then I understood it correctly, will review now!

**Review by Alportan — APPROVED** [review]
Looks good! 🥳

**Pull request merged**
