### PR TITLE
Upgrade vite

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

Some of our dependencies are starting to drift.
closes: #5213
closes: #5215 

## Description

This PR updates vite to v4.2.1 to make sure our dependencies don't drift too much, as far as my local testing shows there should be no issues. This is also a prerequestite to ensure we can upgrade to typescript 5.

### Double check

- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Not really sure why cypress e2e is failing here since it's working for me locally but I think it's a caching issue in the action. So if it passes for you guys locally it should be safe to merge.

**Comment by tonypls** [comment]
> Not really sure why cypress is failing, vite 4 is supported per their own documentation.

https://github.com/cypress-io/cypress/issues/25913#issuecomment-1465464777

**Comment by VIKTORVAV99** [comment]
> > Not really sure why cypress is failing, vite 4 is supported per their own documentation.
> 
> https://github.com/cypress-io/cypress/issues/25913#issuecomment-1465464777

I guess we are waiting then 😅

I'll turn this into a draft in the meantime.

**Comment by VIKTORVAV99** [comment]
Cypress 12.9.0 was released that fixes our issues in this PR so I have re-opened and bumped cypress.

Let me know if you want me to bump any other packages in conjunction with this or if we should proceeded with them as individual PRs.

**Comment by tonypls** [comment]
If you haven't already, because of the lockfile change could you also upgrade pnpm to version 8 then run ```pnpm i --fix-lockfile```


We had a similar issue to [this](https://github.com/pnpm/action-setup/issues/40) effecting deployment

**Comment by VIKTORVAV99** [comment]
> If you haven't already, because of the lockfile change could you also upgrade pnpm to version 8 then run `pnpm i --fix-lockfile`
> 
> We had a similar issue to [this](https://github.com/pnpm/action-setup/issues/40) effecting deployment

I have not, but I will do that right away!

**Review by tonypls — APPROVED** [review]
LGTM 🎉

**Pull request merged**
