### PR TITLE
Uses US proxy for CA_QC parser

### PR DESCRIPTION
**Pull request by madsnedergaard**
### Issue
#5294

### Summary
🇺🇸🛠️💡

Updated `CA_QC` parser to use a proxy service for accessing Hydro Quebec data. This fixes the issue of the parser failing for non-Canadian IPs.

> _`Hydro Quebec` blocked_
> _use proxy to fetch data_
> _issue fixed in fall_

### Walkthrough
*  Modify the URLs for fetching production and consumption data from Hydro Quebec to use a US proxy service ([link](https://github.com/electricitymaps/electricitymaps-contrib/pull/5304/files?diff=unified&w=0#diff-90558155ad86f732c758ade053f92fd19cca9b47650800a8bd5fcb8df3a2d6e6L10-R14)). This fixes issue #3432, which caused the parser to fail for non-Canadian IP addresses. The proxy service appends a `host` parameter to the request to indicate the original URL.

### CODE REVIEW

**Review by VIKTORVAV99 — COMMENTED** [review]
This is failing for me locally with the following traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\vikto\Kod\electricitymap-contrib\.venv\lib\site-packages\click\core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vikto\Kod\electricitymap-contrib\.venv\lib\site-packages\click\core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "C:\Users\vikto\Kod\electricitymap-contrib\.venv\lib\site-packages\click\core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vikto\Kod\electricitymap-contrib\.venv\lib\site-packages\click\core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\vikto\Kod\electricitymap-contrib\test_parser.py", line 60, in test_parser
    res = parser(*args, target_datetime=target_datetime, logger=getLogger(__name__))
  File "C:\Users\vikto\Kod\electricitymap-contrib\parsers\CA_QC.py", line 45, in fetch_production
    data = _fetch_quebec_production(session)
  File "C:\Users\vikto\Kod\electricitymap-contrib\parsers\CA_QC.py", line 108, in _fetch_quebec_production
    return response.json()
  File "C:\Users\vikto\Kod\electricitymap-contrib\.venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I don't have time to dig into this right away but if it's still an issue later today I'll take a look.

**Comment by madsnedergaard** [comment]
> This is failing for me locally with the following traceback:
> ...
> I don't have time to dig into this right away but if it's still an issue later today I'll take a look.

As mentioned in PR description this is still awaiting a PR on the internal proxy code that enables this host, so it shouldn't actually work yet 😄 
I'll test it once the proxy is ready and update here if it does not work as expected.

**Comment by madsnedergaard** [comment]
Works now :)

**Comment by VIKTORVAV99** [comment]
Apparently this PR fixes #3432 though. I think Copilot might be a little confused 😅

I'll give it a quick test locally but shouldn't be any issues

**Comment by madsnedergaard** [comment]
> Apparently this PR fixes #3432 though. I think Copilot might be a little confused 😅
> 
> I'll give it a quick test locally but shouldn't be any issues

Haha yeah, don't know how it found that issue 😂 

Fixed screenshot from local testing: 
Screenshot 2023-04-21 at 15 37 03

**Review by VIKTORVAV99 — APPROVED** [review]
Let's get the data flowing!

**Pull request merged**
