### PR TITLE
Add v8 mockdata

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Description

This adds v8 mock data, updates the v7 mock data and removes the v6 mock data that are no longer in use.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
This is in case I get bored in the middle of the woods and want to work with no internet connection 😅

**Review by madsnedergaard — APPROVED** [review]
LGTM :)

**Comment by tonypls** [comment]
It seems this PR may have impacted the Cypress tests on master, as there's an issue with the zone details API not loading the expected data.

**Comment by VIKTORVAV99** [comment]
> It seems this PR may have impacted the Cypress tests on master, as there's an issue with the zone details API not loading the expected data.

I'll take care of it!

**Comment by madsnedergaard** [comment]
Any news on this, @VIKTORVAV99? This PR introduced different dates for the state and the details files (2022 vs 2023) :)
Also happy to help out if you're busy

**Comment by VIKTORVAV99** [comment]
> Any news on this, @VIKTORVAV99? This PR introduced different dates for the state and the details files (2022 vs 2023) :) Also happy to help out if you're busy

I thought it would be a quick fix, but for some unknown reason the details and state files are out of sync by days by the look of it. And when I tired to update them again I got the same issue.

I'll see if I can download some new data later today and hopefully they will be in sync...

**Comment by madsnedergaard** [comment]
I just realised you also fixed this in the v8 branch, so I'm wondering if we should split out the mockserver/cy-testing part from that PR or try to get the whole thing reviewed and merged soon? :)

**Comment by VIKTORVAV99** [comment]
> I just realised you also fixed this in the v8 branch, so I'm wondering if we should split out the mockserver/cy-testing part from that PR or try to get the whole thing reviewed and merged soon? :)

They are kind of tied hand in hand as the tests should reflect that the app is calling a new endpoint. But I have been testing the preview branch a bunch and so far I have not found any issues besides those I solved yesterday. So we could just go forward with that.

But I had hoped we could sneak in a fix for the GFS data structure being different between the endpoints but I suppose we could do that later on as it calls another endpoint.

**Pull request merged**
