### PR TITLE
chore: Update CODEOWNERS to include teams

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Description

Now that we have teams in github we should take advantage of that 🙂

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
> Hmm, will this not notify the whole team? 🤔

It should just automatically assign one person for review since we have auto assignment on for Avo. So I hope not...

It will however notify the self-service team 😉

**Review by madsnedergaard — APPROVED** [review]
Let's try, then we can readjust later if required :)
(On a side-note we could in the future create sub-teams like `self-service/engineering` or something like that, so it doesn't notify the full team)

**Comment by VIKTORVAV99** [comment]
@tonypls what do you think about this?

**Review by tonypls — APPROVED** [review]
LGTM, let's try it out!

**Pull request merged**
