### PR TITLE
refactor: remove arrow from SG parser

### PR DESCRIPTION
**Pull request by yujia21**
## Issue
[6135](https://github.com/electricitymaps/electricitymaps-contrib/issues/6135)

## Description

Removes arrow module from parser, replacing with `datetime`.

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — CHANGES_REQUESTED** [review]
Thanks for creating a PR!

Just took a quick glance at this and will do a full review next week but it seems like the datetimes returned don't match what is returned on master right now. There is a 7 hour difference right now.

**Comment by yujia21** [comment]
> Thanks for creating a PR!
> 
> Just took a quick glance at this and will do a full review next week but it seems like the datetimes returned don't match what is returned on master right now. There is a 7 hour difference right now.

Argh, could you give me the steps to reproduce it?
In my local, on master branch I have:
```
(.venv) $ python3 parsers/SG.py 
fetch_production() ->
{'datetime': datetime.datetime(2023, 12, 17, 9, 0, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Singapore')), 'zoneKey': 'SG', 'production': defaultdict(<class 'float'>, {'gas': 5644.129, 'unknown': 127.09400000000001, 'solar': 204.15, 'nuclear': 0, 'wind': 0, 'hydro': 0}), 'storage': {}, 'source': 'emcsg.com, ema.gov.sg'}
fetch_price("SG") ->
{'zoneKey': 'SG', 'datetime': datetime.datetime(2023, 12, 17, 9, 0, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Singapore')), 'currency': 'SGD', 'price': 96.52, 'source': 'emcsg.com'}
```
Then on this branch
```
(.venv) $ python3 parsers/SG.py 
fetch_production() ->
{'datetime': datetime.datetime(2023, 12, 17, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='Asia/Singapore')), 'zoneKey': 'SG', 'production': defaultdict(<class 'float'>, {'gas': 5644.129, 'unknown': 127.09400000000001, 'solar': 204.15, 'nuclear': 0, 'wind': 0, 'hydro': 0}), 'storage': {}, 'source': 'emcsg.com, ema.gov.sg'}
fetch_price("SG") ->
{'zoneKey': 'SG', 'datetime': datetime.datetime(2023, 12, 17, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='Asia/Singapore')), 'currency': 'SGD', 'price': 96.52, 'source': 'emcsg.com'}

The only difference I see is in the tzinfo but both should be in the Asia/Singapore timezone.

**Comment by VIKTORVAV99** [comment]
> > Thanks for creating a PR!
> 
> > 
> 
> > Just took a quick glance at this and will do a full review next week but it seems like the datetimes returned don't match what is returned on master right now. There is a 7 hour difference right now.
> 
> 
> 
> Argh, could you give me the steps to reproduce it?
> 
> In my local, on master branch I have:
> 
> ```
> 
> (.venv) $ python3 parsers/SG.py 
> 
> fetch_production() ->
> 
> {'datetime': datetime.datetime(2023, 12, 17, 9, 0, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Singapore')), 'zoneKey': 'SG', 'production': defaultdict(<class 'float'>, {'gas': 5644.129, 'unknown': 127.09400000000001, 'solar': 204.15, 'nuclear': 0, 'wind': 0, 'hydro': 0}), 'storage': {}, 'source': 'emcsg.com, ema.gov.sg'}
> 
> fetch_price("SG") ->
> 
> {'zoneKey': 'SG', 'datetime': datetime.datetime(2023, 12, 17, 9, 0, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Singapore')), 'currency': 'SGD', 'price': 96.52, 'source': 'emcsg.com'}
> 
> ```
> 
> Then on this branch
> 
> ```
> 
> (.venv) $ python3 parsers/SG.py 
> 
> fetch_production() ->
> 
> {'datetime': datetime.datetime(2023, 12, 17, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='Asia/Singapore')), 'zoneKey': 'SG', 'production': defaultdict(<class 'float'>, {'gas': 5644.129, 'unknown': 127.09400000000001, 'solar': 204.15, 'nuclear': 0, 'wind': 0, 'hydro': 0}), 'storage': {}, 'source': 'emcsg.com, ema.gov.sg'}
> 
> fetch_price("SG") ->
> 
> {'zoneKey': 'SG', 'datetime': datetime.datetime(2023, 12, 17, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='Asia/Singapore')), 'currency': 'SGD', 'price': 96.52, 'source': 'emcsg.com'}
> 
> ```
> 
> 
> 
> The only difference I see is in the tzinfo but both should be in the Asia/Singapore timezone.

I just ran it first on master then this branch, but I'll see if I can dig into why it's happening later today or tomorrow.

**Comment by VIKTORVAV99** [comment]
When run on your branch I get this:
```
{'datetime': datetime.datetime(2023, 12, 19, 23, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Singapore')),
 'production': defaultdict(<class 'float'>,
                           {'gas': 6809.3251,
                            'hydro': 0,
                            'nuclear': 0,
                            'solar': 91.81,
                            'unknown': 122.3024,
                            'wind': 0}),
 'source': 'emcsg.com, ema.gov.sg',
 'storage': {},
 'zoneKey': 'SG'}
 ```

When run on master I get this:
```
{'datetime': datetime.datetime(2023, 12, 19, 16, 30, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Singapore')),
 'production': defaultdict(<class 'float'>,
                           {'gas': 6809.3251,
                            'hydro': 0,
                            'nuclear': 0,
                            'solar': 91.81,
                            'unknown': 122.3024,
                            'wind': 0}),
 'source': 'emcsg.com, ema.gov.sg',
 'storage': {},
 'zoneKey': 'SG'}
 ```

I suspect there is a non localised datetime somewhere in there that is causing issues but have not had the time to really dig though the code yet.

**Comment by yujia21** [comment]
@VIKTORVAV99 I've added a commit with a patch to fix it, running it with `TZ='Europe/Stockholm' python3 parsers/SG.py` showed the time difference in my local previously but is now correct.

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM!

Thanks for removing arrow in this parser!

**Pull request merged**
