### PR TITLE
Add and fix some French translations

### PR DESCRIPTION
**Pull request by phiphou**
Add and fix some French translations.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
There don't seem to be any changes in this PR?

**Comment by phiphou** [comment]
> There don't seem to be any changes in this PR?

My bad, forgot to sync after my commit.

Just fixed that...

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Comment by VIKTORVAV99** [comment]
No problem! I suspected something along those lines!

**Pull request merged**
