### PR TITLE
Fix: Allow Origin Chart source selection on mobile

### PR DESCRIPTION
**Pull request by cadeban**
## Description
Currently the Origin Chart source selection doesn't work on mobile (to test, toggle device in devtools). This PR fixes that by removing the 'sm' prefix from graph layer styling.

### Preview
**Before & After:**
Screenshot 2024-11-18 at 11 31 49Screenshot 2024-11-18 at 11 31 31

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by cadeban** [comment]
Would like to fit this in before I do a mobile release

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Comment by VIKTORVAV99** [comment]
I was actually going to take a look at this myself but thanks for being proactive about it!

**Comment by cadeban** [comment]
Great minds! 😉

**Pull request merged**
