### PR TITLE
Feat: Add labels for chart

### PR DESCRIPTION
**Pull request by cadeban**
## Description
Add labels for chart source icons and remove tooltip legend.

### Preview
Screenshot 2024-11-01 at 11 10 57
Screenshot 2024-11-01 at 11 11 17
Screenshot 2024-11-01 at 11 11 36

Added flex wrap so the above whitespace is a little awkward^
Screenshot 2024-11-01 at 11 18 29

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by cadeban** [comment]
@Alportan Added labels for the legend per our conversation in the SoMe sesh. Would love your feedback!

Question I had: Should we consider sorting the sources alphabetically? Or perhaps grouping renewables before fossil fuels?

**Comment by VIKTORVAV99** [comment]
> @Alportan & @VIKTORVAV99 Added labels for the legend per our conversation in the SoMe sesh. Would love your feedback!
> 
> Question I had: Should we consider sorting the sources alphabetically? Or perhaps grouping renewables before fossil fuels?

Not sure about alphabetical sorting but we do have some sorting and grouping in the bar breakdown chart. Basically these groups: controlled renewable, uncontrolled (solar, wind), nuclear, storage, fossil.

There has been some debate if these still make sense though.

**Comment by VIKTORVAV99** [comment]
If we do use alphabetical sorting we should use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator and still put unknown/other last regardless IMO.

**Comment by cadeban** [comment]
I changed the font size, weight, and color too:
Screenshot 2024-11-01 at 15 44 35

Screenshot 2024-11-01 at 15 44 45

**Comment by tonypls** [comment]
Looks great! I would reverse the order so both the legend and the chart read top to bottom.

**Review by tonypls — APPROVED** [review]
LGTM 🎉

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

Love that red diff again!

**Pull request merged**
