### PR TITLE
Add configuration for aggregation of India

### PR DESCRIPTION
**Pull request by unitrium**
## Issue

We are going to release IN-EA and IN-NE soon. Therefore we could enable an aggregation of India.

## Description

Writes the configuration to enable an aggregation of India.

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — COMMENTED** [review]
Just one slight issue, we have one more India zone 😅
https://app.electricitymaps.com/zone/IN-AN

However we could do what we did for the US?

**Comment by unitrium** [comment]
I just added it to the English translation for now

**Comment by VIKTORVAV99** [comment]
> I just added it to the English translation for now

Nice! However I think Mainland India is technically more correct (don't quote me on this one though).

I see the Bangladesh exchange is missing in the aggregated view, I can add it if you want?

**Comment by unitrium** [comment]
> > I just added it to the English translation for now
> 
> Nice! However I think Mainland India is technically more correct (don't quote me on this one though).
> 
> I see the Bangladesh exchange is missing in the aggregated view, I can add it if you want?

Indeed!

**Review by VIKTORVAV99 — APPROVED** [review]
So it was! 😅

This looks good to me, let's get it merged.

**Pull request merged**
