### PR TITLE
Update unknown capacity for SV

### PR DESCRIPTION
**Pull request by pierresegonne**
## Issue

The `SV` parser seemingly aggregates all thermal into unknown -> We need the capacity to reflect this otherwise we're excluding most data points in the quality validator

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Review by mathilde-daugy — APPROVED** [review]

**Comment by pierresegonne** [comment]
Thanks for the pointer, there was also a mistake with the geothermal capacity

**Comment by mathilde-daugy** [comment]
why a mistake? we do get geothermal data? 
image

**Comment by pierresegonne** [comment]
> why a mistake? we do get geothermal data?

There was no geothermal capacity declared, and instead the 200MW where attributed to unknonw

**Comment by q--** [comment]
Could this perhaps also be happening for Thailand?

**Comment by VIKTORVAV99** [comment]
> > we're excluding most data points in the quality validator
> 
> 
> 
> Could this perhaps also be happening for Thailand?
> 
> 
> 
> 

We are looking into it!

**Pull request merged**
