### PR TITLE
Fix GB Parser

### LINKED ISSUE #6068: GB production parser down
## Description

This is an automatic error report generated for Great Britain (GB).

Issues:
- No recent data found for `consumption` parser
- No recent data found for `consumptionForecast` parser
- No recent data found for `generationForecast` parser
- No recent data found for `price` parser
- No recent data found for `production` parser
- No recent data found for `productionPerModeForecast` parser

## Suggestions
- Try running the parser locally using the command `poetry run test_parser GB production`
- <a href="https://storage.googleapis.com/electricitymap-parser-logs/GB.html">Explore the runtime logs</a>

You can see an overview of all parser issues [here](https://github.com/electricitymaps/electricitymaps-contrib/wiki/Parser-issues).

### PR DESCRIPTION
**Pull request by JRascagneres**
## Issue

Closes #6068

## Description

Fixes the GB parser. Essentially the checks for number of fields were failing - this is because GB is getting a new interconnector - "Viking Link" which has been added to the API output, thus adding a new field.

### Double check

- [X] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Comment by JRascagneres** [comment]
@VIKTORVAV99 Hey, whats the timeline on review for this? Fairly small PR and the GB parsing has been broken for a good few weeks now, affecting folk like HA users data

**Comment by VIKTORVAV99** [comment]
I'm going to take a look at this today.

**Comment by JRascagneres** [comment]
👌

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

Thanks for fixing it!

**Pull request merged**
