### PR TITLE
Fix: production history shows mt instead of kg

### LINKED ISSUE #4317: Tooltip of production history shows mt instead of kg for unit of emissions
See this screenshot:
image

Similar to #793.

### PR DESCRIPTION
**Pull request by wrma6**
## Issue

Closes #4317 

## Description

This should be the fix for [this open issue](https://github.com/electricitymaps/electricitymaps-contrib/issues/4317), just one simple change in the end. The issue seems to be that the value used for comparison in `formatCo2` is the parameter that uses units `gCO₂ / h` instead of the final calculated value (that is the number formatted) that uses units `tCO₂ / min`.

### Preview

image

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Comment by wrma6** [comment]
@jarek I saw that you responded to the original issue, are you the right person to ask for review?

**Comment by jarek** [comment]
Thanks for making the PR! As far I know, @VIKTORVAV99 should be best for reviewing front-end PRs.

**Comment by VIKTORVAV99** [comment]
Yep that would be me, I'll take a look at this as soon as possible.

Thanks for the mention @jarek.

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

Thanks for fixing it @wrma6!

**Pull request merged**
