### PR TITLE
bug(web): Remove check for loaded source (again)

### LINKED ISSUE #6136: [Bug] [Firefox] Zone consumption data greyed-out on map after initial page-load
**Describe the bug**
When the `electricitymap` app page is opened, initially the zone consumption data appears to be missing -- all of the zone polygons are displayed in grey.  Cross-border exports do appear as expected, however.

Workaround: toggle the time from the default of 'live' to an hour ago and then back again -- or toggle the view mode from the default of 'consumption' to 'production' and back again.

**To Reproduce**
1. https://app.electricitymaps.com/map
2. Observe that the country zone polygons are coloured grey initially.

**Expected behavior**

**Screenshots**
image

**Desktop:**
 - OS: Debian Trixie (13) GNU/Linux
 - Browser: Firefox
 - Version: 115.4.0

**Additional context**
This is a problem that I've only noticed within the past week -- making me think that it could be a regression.

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
Trying to fix #6136 

Map sometimes loads as gray on Firefox

## Description
This PR adds a onload useEffect that calls a colorZones call back to color the map when the sources are loaded

Draft to get some feedback @jayaddison or @strassburger Could you try replicate the bug on this branch for me? 🙏  [Preview here](https://a32116e2.electricitymaps-staging.pages.dev/)

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Comment by jayaddison** [comment]
Thank you for taking a look at this @tonypls!

Good news and bad news for you, based on using the [staging preview site](https://a32116e2.electricitymaps-staging.pages.dev/map).

  * The good news: I can't replicate the greyed-out zone polygons any more - when they appear at page-load, they appear filled in colour.
  * The bad news: I occassionally (~10% of page loads) see a different problem now - a loading spinner continues to appear and the map does not.

image

**Comment by strassburger** [comment]
Aahh, found the Link:
https://a32116e2.electricitymaps-staging.pages.dev/map
That link works fine with me.
Thanks a lot for that good job of @tonypls

**Comment by strassburger** [comment]
@jayaddison,
You discribed a new problem:
 " The bad news: I occassionally (~10% of page loads) see a different problem now - a loading spinner continues to appear and the map does not."

could it be tests  after full hours?
At beginning of new hours i have seen that problem a few times. Looks like the server is busy at beginning of new hour to calculate data. That problem is independent of the patch of @tonypls, i think.

**Comment by jayaddison** [comment]
> @jayaddison, You discribed a new problem: " The bad news: I occassionally (~10% of page loads) see a different problem now - a loading spinner continues to appear and the map does not."
> 
> could it be tests after full hours? At beginning of new hours i have seen that problem a few times. Looks like the server is busy at beginning of new hour to calculate data. That problem is independent of the patch of @tonypls, i think.

Hmm.. no, I don't think it's related to the time when the page is loaded @strassburger - I was able to replicate the problem a few moments ago (~58 minutes past the hour).  There's always a chance that it's related to something server-side, but in this case I think that it is a client-side behaviour only.

**Comment by VIKTORVAV99** [comment]
Oh it seems to actually have some good suggestions!

**Comment by Ugzuzg** [comment]
Fixes the issue for me on Firefox for Android.

**Comment by Ugzuzg** [comment]
The main issue is that `isSourceLoaded` inside the effect that renders the zones is not reactive and the change of the source state doesn't trigger a re-render of the component. Subscribing to that and changing the state fixes the issue:

```diff
diff --git a/web/src/features/map/Map.tsx b/web/src/features/map/Map.tsx
index 8225f7f6..ffe6db8a 100644
--- a/web/src/features/map/Map.tsx
+++ b/web/src/features/map/Map.tsx
@@ -59,6 +59,7 @@ export default function MapPage({ onMapLoad }: MapPageProps): ReactElement {
   const [selectedDatetime] = useAtom(selectedDatetimeIndexAtom);
   const setLeftPanelOpen = useSetAtom(leftPanelOpenAtom);
   const [isFirstLoad, setIsFirstLoad] = useState(true);
+  const [isSourceLoaded, setSourceLoaded] = useState(false);
   const location = useLocation();
   const getCo2colorScale = useCo2ColorScale();
   const navigate = useNavigate();
@@ -76,6 +77,26 @@ export default function MapPage({ onMapLoad }: MapPageProps): ReactElement {
   const mapReference = useRef<MapRef>(null);
   const map = mapReference.current?.getMap();
 
+  useEffect(() => {
+    const setSourceLoadedForMap = () => {
+      setSourceLoaded(
+        Boolean(
+          map &&
+            map.getSource(ZONE_SOURCE) !== undefined &&
+            map.getSource('states') !== undefined &&
+            map.isSourceLoaded('states')
+        )
+      );
+    };
+    const onSourceData = () => {
+      setSourceLoadedForMap();
+    };
+    map?.on('sourcedata', onSourceData);
+    return () => {
+      map?.off('sourcedata', onSourceData);
+    };
+  }, [map]);
+
   useEffect(() => {
     // This effect colors the zones based on the co2 intensity
     if (!map || isLoading || isError) {
@@ -83,11 +104,6 @@ export default function MapPage({ onMapLoad }: MapPageProps): ReactElement {
     }
     map?.touchZoomRotate.disableRotation();
     map?.touchPitch.disable();
-    const isSourceLoaded =
-      map &&
-      map.getSource(ZONE_SOURCE) !== undefined &&
-      map.getSource('states') !== undefined &&
-      map.isSourceLoaded('states');
 
     if (!isSourceLoaded || isLoadingMap) {
       return;
@@ -120,11 +136,13 @@ export default function MapPage({ onMapLoad }: MapPageProps): ReactElement {
       }
     }
   }, [
+    map,
     data,
     getCo2colorScale,
     selectedDatetime,
     mixMode,
     isLoadingMap,
+    isSourceLoaded,
     spatialAggregate,
     isSuccess,
   ]);
@@ -138,7 +156,7 @@ export default function MapPage({ onMapLoad }: MapPageProps): ReactElement {
       map.flyTo({ center: [data.callerLocation[0], data.callerLocation[1]] });
       setIsFirstLoad(false);
     }
-  }, [isSuccess]);
+  }, [map, isSuccess]);
 
   useEffect(() => {
     // Run when the selected zone changes
@@ -170,7 +188,7 @@ export default function MapPage({ onMapLoad }: MapPageProps): ReactElement {
       const centerMinusLeftPanelWidth = [center[0] - 10, center[1]] as [number, number];
       map.flyTo({ center: isMobile ? center : centerMinusLeftPanelWidth, zoom: 3.5 });
     }
-  }, [location.pathname, isLoadingMap]);
+  }, [map, location.pathname, isLoadingMap]);
 
   const onClick = (event: mapboxgl.MapLayerMouseEvent) => {
     if (!map || !event.features) {
```

Adding `map` to a dependency list of the effects makes sure that the map reference doesn't get stale in the closure and fixes the hot reload issue on my machine.

**Comment by tonypls** [comment]
Closed thanks to @Ugzuzg 🙏

**Pull request closed without merging**
