### PR TITLE
fix: Quick fix for the rounding logic in analyzeChartData

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Description
Quick fix for the math in the function.

### Double check

- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Review by silkeholmebonnen — COMMENTED** [review]
What is FORECASTS_HIERARCHY and is it equivalent to TSA?

**Comment by VIKTORVAV99** [comment]
> What is FORECASTS_HIERARCHY and is it equivalent to TSA?

Because it's the same as the TSA model but it replaces the solar and wind output with forecasts from ENTSO-E when they are available.

**Comment by silkeholmebonnen** [comment]
It seems a bit weird that the aggregated percentage is larger than any of the years it is aggregating. Do you know why this happens?


https://github.com/user-attachments/assets/e2c7a763-589d-49ff-9eb8-87bcf2c55515

**Comment by VIKTORVAV99** [comment]
> It seems a bit weird that the aggregated percentage is larger than any of the years it is aggregating. Do you know why this happens?
> 
>  calc.mov

The multiplication was in the wrong side of the parentheses 🤦🏻‍♂️

**Review by silkeholmebonnen — APPROVED** [review]
LGTM! 

I still think that we should think about if we want to hide the estimation percentage if e.g. only one datapoint is estimated. But this we can figure that out after, let's merge this!

**Pull request merged**
