### PR TITLE
feat(zone-config): update discharge emission factors for all zones

### PR DESCRIPTION
**Pull request by silkeholmebonnen**
## Issue

[AVO-475](https://linear.app/electricitymaps/issue/AVO-475/update-discharge-emission-factors-for-all-zones)

## Description

This PR updates the discharge emission factors for all zones using the script `update_co2eq_parameters_overrides.py`. Unfortunately it also makes a bunch of formatting changes (I'm sorry reviewer).

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by silkeholmebonnen** [comment]
Should I update the test to match the new emission factors?

**Comment by VIKTORVAV99** [comment]
> Should I update the test to match the new emission factors?

Yes :)

**Comment by VIKTORVAV99** [comment]
If possible could we round the output to 2 decimals?

**Comment by FelixDQ** [comment]
It would be nice to have a pre-commit or script that ensures the keys are always in the same order. It's kind of impossible to review PRs like this. I guess that we'll have to trust the script for now

**Comment by VIKTORVAV99** [comment]
> It would be nice to have a pre-commit or script that ensures the keys are always in the same order. It's kind of impossible to review PRs like this. I guess that we'll have to trust the script for now

Most of the changes should be easy to review, it's only a couple of manually edited files that are out of order (they where not sorted by key before).

I'll see about either adding a pre-commit hook for it, or a simple check in the CI, or both for future PRs.

**Comment by silkeholmebonnen** [comment]
How can I test this locally? 

I have tried running `poetry run test` from contrib but it fails with the error message:

⚙︎ pytest 
/bin/sh: /Users/sshb/Desktop/emaps/electricitymaps/contrib/.venv/bin/pytest: /Users/sshb/Desktop/electricitymaps/contrib/.venv/bin/python: bad interpreter: No such file or directory
FAILED: pytest

**Comment by silkeholmebonnen** [comment]
> If possible could we round the output to 2 decimals?

Yes, but it would require an update to the script. But do we want to lose the precision of the numbers?

**Review by FelixDQ — APPROVED** [review]
Let's go ahead with the current precision. We can adjust later

**Comment by madsnedergaard** [comment]
> > If possible could we round the output to 2 decimals?
> 
> Yes, but it would require an update to the script. It's an easy fix and I already tried to run it but do we want to lose the precision of the numbers?

For future I would say yes, the precision doesn't help us (we only show 2 decimals in app anyway) and might make people believe it's extremely accurate :)

Here's a previous discussion on the topic: https://github.com/electricitymaps/electricitymaps-contrib/issues/6345

**Comment by silkeholmebonnen** [comment]
> > > If possible could we round the output to 2 decimals?
> > 
> > 
> > Yes, but it would require an update to the script. It's an easy fix and I already tried to run it but do we want to lose the precision of the numbers?
> 
> For future I would say yes, the precision doesn't help us (we only show 2 decimals in app anyway) and might make people believe it's extremely accurate :)
> 
> Here's a previous discussion on the topic: #6345

I created a slack friendly task for this: [AVO-561](https://linear.app/electricitymaps/issue/AVO-561/round-discharge-emission-factors)

**Pull request merged**
