### PR TITLE
Update BG capacities

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue
closes: #5386 

## Description

Updates the capacities for Bulgaria. Split of from #5398.

### Double check

- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Comment by madsnedergaard** [comment]
Is data source still the same (ENTSOE + NEK for hydro)? :)

**Comment by VIKTORVAV99** [comment]
> Is data source still the same (ENTSOE + NEK for hydro)? :)

Oh this is just ENTSO-E, I'll see if it's in line with NEK as well.

**Comment by VIKTORVAV99** [comment]
NEK has not been updated and ENTSO-E has been using these values for a while now so I'll revert hydro to using the NEK values.

**Review by madsnedergaard — APPROVED** [review]
Great, thanks!

**Pull request merged**
