### PR TITLE
tmp-fix(FR parser): switch FR production parser to ENTSO-E

### PR DESCRIPTION
**Pull request by unitrium**
## Issue

From @florianscheidl's investigations: the FR parser is currently not working returning only timestamps and no data. Because of the long week-end we cannot expect any fix before next week earliest. 

## Description

Switch temporarely FR to ENTSO-E until we have an update on the parser.

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
I'll regenerate the lock file as that is failing for some reason.

**Comment by VIKTORVAV99** [comment]
Just note that this will be blocked in the monorepo unless the current ruff stuff is merged first.

**Comment by unitrium** [comment]
Which ruff stuff @VIKTORVAV99 ?

**Comment by VIKTORVAV99** [comment]
> Which ruff stuff @VIKTORVAV99 ?

This https://github.com/electricitymaps/electricitymaps/pull/5047

Since the ruff PR has already been merged in contrib it needs the corresponding monorepo changes or the update contrib job won't work due to the lock files being out of sync.

**Comment by unitrium** [comment]
Ok then let's get them merged asap if we can as FR is a priority zone, otherwise if it's breaking too many things in the mono repo we should revert the ruff PR.

**Comment by VIKTORVAV99** [comment]
> Ok then let's get them merged asap if we can as FR is a priority zone, otherwise if it's breaking too many things in the mono repo we should revert the ruff PR.

As far as I can tell it's just small formatting and syntax changes. And should not be breaking but I didn't want to merge it without another set of eyes on it first.

**Review by florianscheidl — APPROVED** [review]
LGTM, I checked if it would make sense to change to the ENTSO-E consumption data as well but they also do not have consumption data atm, so only changing production seems good 👍.

**Comment by florianscheidl** [comment]
I'd support fixing the parser on the monorepo for now and merging contrib early next week to avoid things breaking on long-weekend Friday?

**Comment by florianscheidl** [comment]
> > Ok then let's get them merged asap if we can as FR is a priority zone, otherwise if it's breaking too many things in the mono repo we should revert the ruff PR.
> 
> As far as I can tell it's just small formatting and syntax changes. And should not be breaking but I didn't want to merge it without another set of eyes on it first.

Or we can go for that 👍

**Review by VIKTORVAV99 — APPROVED** [review]
Let's merge this either way, I don't expect the ruff PR to be a issue.

**Pull request merged**
