### PR TITLE
Update capacity of FR<->GB interconnectors

### PR DESCRIPTION
**Pull request by q--**
Support for the ElecLink interconnector between France and Great Britain was added in #2840. This PR adds the capacity + a data source for said capacity.

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

For some reason the CI is failing (unrelated to this PR) and once that is sorted I'll merge this.

**Comment by q--** [comment]
Oh, I thought it was me. Currently struggling with installing the web dependencies. Well, I almost got the problem with my conflicting installed yarn versions sorted anyway.

**Comment by VIKTORVAV99** [comment]
> Oh, I thought it was me. Currently struggling with installing the web dependencies. Well, I almost got the problem with my conflicting installed yarn versions sorted anyway.

Oh, we don't use yarn anymore 😅
We switched to PNPM in the re-write but it looks like we forgot to update all the mentions of it 😅

**Comment by VIKTORVAV99** [comment]
@q-- sorry for the confusion about yarn and PNPM in here. If you wish I can update the config files that the CI is complaining about. It shouldn't be needed but we changed how things work in the rewrite and this particular part was overlooked. We'll hopefully have a fix for it soon.

**Comment by VIKTORVAV99** [comment]
@q-- I generated the new zone config so we can get this merged, hopefully we will remove this dependency on generating config changes soon!

**Pull request merged**
