### PR TITLE
4574-nl-production-parser-down

### PR DESCRIPTION
**Pull request by mathilde-daugy**
## Description

fixed TypeError: can't compare offset-naive and offset-aware datetimes in fetch_production

### Preview

N/A

### CODE REVIEW

**Review by pierresegonne — COMMENTED** [review]
Doesn't the change of index create an issue?

**Comment by mathilde-daugy** [comment]
> Doesn't the change of index create an issue?

removing the index fixes the type error

**Comment by mathilde-daugy** [comment]
turns out the parser was down because of PR [4258](https://github.com/electricitymaps/electricitymaps-contrib/pull/4528)

**Comment by pierresegonne** [comment]
Alright if you've tested it, feel free to merge then :)

**Review by pierresegonne — APPROVED** [review]
giphy

**Pull request merged**
