### PR TITLE
Silkebonnen/ele 3346 add estimation label to each graph that is indeed estimated

### PR DESCRIPTION
**Pull request by silkeholmebonnen**
## Issue

[ELE-3346](https://linear.app/electricitymaps/issue/ELE-3346/add-estimation-label-to-each-graph-that-is-indeed-estimated)

## Description

The goal of this PR is to increase transparency about what data has been estimated. This is done by added a _Estimated_ label to each graph that is estimated and to the tooltips of these graphs. When hovering over the emissions/carbon intensity/origin of electricity for the last 24 hours you will see an _Estimated_ label for the hours that has been estimated. 

### Preview

**Estimated badge by the graphs that has been estimated**
image
image

**Estimated badge on the tooltip when hovering**
image
image
image
image

**Estimated badge only showing when hovering on hours that has been estimated**
image

**On Phone**
image

### CODE REVIEW

**Comment by q--** [comment]
As for the badge by the graphs, it would be more accurate to label them 'partially estimated' if measured data is available for some hours.

**Review by VIKTORVAV99 — CHANGES_REQUESTED** [review]
One slight issue here, the exchanges are marked as estimated even though they clearly are not cause we don't estimate exchanges yet:
image

**Comment by VIKTORVAV99** [comment]
> As for the badge by the graphs, it would be more accurate to label them 'partially estimated' if measured data is available for some hours.

This is in the plans, we just need to change the backend a bit first.

**Comment by VIKTORVAV99** [comment]
> As for the badge by the graphs, it would be more accurate to label them 'partially estimated' if measured data is available for some hours.

Agreed, we should check all elements in the graph is estimated before marking the whole graph as estimated otherwise we should say partially estimated next to the graph title for clarity.

**Comment by madsnedergaard** [comment]
> > As for the badge by the graphs, it would be more accurate to label them 'partially estimated' if measured data is available for some hours.
> 
> Agreed, we should check if all elements in the graph are estimated before marking the whole graph as estimated otherwise we should say partially estimated next to the graph title for clarity.

I think that makes good sense, happy to work together on this tomorrow morning @silkeholmebonnen :)

**Comment by silkeholmebonnen** [comment]
> One slight issue here, the exchanges are marked as estimated even though they clearly are not cause we don't estimate exchanges yet: image

I've removed it for the exchanges now. Thanks Viktor!

**Comment by silkeholmebonnen** [comment]
> > As for the badge by the graphs, it would be more accurate to label them 'partially estimated' if measured data is available for some hours.
> 
> Agreed, we should check if all elements in the graph are estimated before marking the whole graph as estimated otherwise we should say partially estimated next to the graph title for clarity.

I have changed it to say 'Partially estimated' when some are estimated and 'Estimated' when all are estimated. 
@q-- @VIKTORVAV99

**Comment by q--** [comment]
Looks good!

One slight improvement might be to de-emphasize the 'estimated' warning a bit when data is only unavailable for the last few hours, as that's not very likely to be significantly off. It might help alleviate a bit of alert fatigue and make it easier to distinguish from a longer, more serious outage.

For example:
'Data is currently estimated' warning with text in silver instead of amber and badge text still reading 'Unavailable''

Or with the badge reading 'Delayed' instead of 'Unavailable'
'Data is currently estimated' warning with text in silver instead of amber and badge text changed to 'Delayed'

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

Thanks for making the changes!

**Comment by VIKTORVAV99** [comment]
> Looks good!
> 
> One slight improvement might be to de-emphasize the 'estimated' warning a bit when data is only unavailable for the last few hours, as that's not very likely to be significantly off. It might help alleviate a bit of alert fatigue and make it easier to distinguish from a longer, more serious outage.
> 
> For example: 'Data is currently estimated' warning with text in silver instead of amber and badge text still reading 'Unavailable''
> 
> Or with the badge reading 'Delayed' instead of 'Unavailable': 'Data is currently estimated' warning with text in silver instead of amber and badge text changed to 'Delayed'

We will likely be tweaking and adjusting this in the future but for the first version we want to be abundantly clear. I'll make sure we take a note of the feedback though.

**Comment by silkeholmebonnen** [comment]
@madsnedergaard Do you also wan't to take a look at it, if you have time?

**Review by madsnedergaard — APPROVED** [review]
LGTM 🙏

**Comment by VIKTORVAV99** [comment]
> ## Suspect Issues
> This pull request was deployed and Sentry observed the following issues:
> 
> * ‼️ **React ErrorBoundary TypeError: o is null** `getExchangeTooltipData(src/features/charts/tool...` [View Issue](https://electricitymaps.sentry.io/issues/4930849366/?referrer=github-pr-bot)
> 
> Did you find this useful? React with a 👍 or 👎

This PR is not the cause of this.

**Pull request merged**
