### PR TITLE
 FR_O parser updates #7280

### PR DESCRIPTION
**Pull request by t-couery**
## Issue

[Data Issue]: Electricity generation at La Réunion (RE) misrepresented #7280 

## Description

The data for Reunion Island was out of date. The mapping has been modified to take account of changes in Biomass.
Data from :

1. RE : Réunion
2. GF : Guyane
3. MQ : Martinique
4. GP : Guadeloupe

have been revised with the updated mapping (minor change on biomas, hydro)
The new 2.1 opendata API is now is now used.

Please note that FR-COR (Corsica) is down due to => Production parser is down #7065 no actual data are available

### Preview

**RE : Réunion**
```
[{'correctedModes': ['gas', 'biomass'],
  'datetime': datetime.datetime(2024, 10, 30, 22, 10, tzinfo=datetime.timezone.utc),
  'production': {'biomass': 241.5738, 'gas': 0, 'hydro': 23.994, 'solar': 3.72, 'wind': 7.044},
  'source': 'opendata-reunion.edf.fr',
  'sourceType': <EventSourceType.estimated: 'estimated'>,
  'storage': {'battery': 2.0432},
  'zoneKey': 'RE'}]
```
Updated: Oil and gas are in fact biomass compared with the present situation :
image

**GF : Guyane** (not updated since 2024-10-16)
```
[ {'correctedModes': [],
  'datetime': datetime.datetime(2024, 10, 16, 12, 1, tzinfo=datetime.timezone.utc),
  'production': {'biomass': 24.590333, 'hydro': 50.852667, 'oil': 155.630666, 'solar': 14.652633},
  'source': 'opendata-guyane.edf.fr',
  'sourceType': <EventSourceType.measured: 'measured'>,
  'storage': {},
  'zoneKey': 'GF'}]
```
No change : Values are identical to the latest data on Electricity MAP :
image

**MQ : Martinique**
```
[{'correctedModes': [],
  'datetime': datetime.datetime(2024, 10, 30, 22, 11, tzinfo=datetime.timezone.utc),
  'production': {'biomass': 45.2378, 'gas': 24.804, 'hydro': 0.0, 'oil': 276.908, 'wind': 0.0},
  'source': 'opendata-martinique.edf.fr',
  'sourceType': <EventSourceType.estimated: 'estimated'>,
  'storage': {},
  'zoneKey': 'MQ'}]
```
Updated: Gas was missing from current data :
image

**GP : Guadeloupe**
```
[{'correctedModes': ['geothermal'],
  'datetime': datetime.datetime(2024, 10, 30, 22, 6, tzinfo=datetime.timezone.utc),
  'production': {'biomass': 23.32,
                 'coal': 27.84,
                 'gas': 0.0,
                 'geothermal': 0,
                 'hydro': 3.168,
                 'oil': 120.248,
                 'solar': 0.0,
                 'wind': 8.046},
  'source': 'opendata-guadeloupe.edf.fr',
  'sourceType': <EventSourceType.estimated: 'estimated'>,
  'storage': {},
  'zoneKey': 'GP'}]
```
No change : Values are consistent with current Electricity MAP :
image

**FR-COR : Corsica**
Down
No data currently available

### Double check

- [X] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [X] I have run `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
> GF : Guyane (not updated since 2024-10-16 and not used on electricity MAP)
We do in fact use this data, it's just delayed a lot so it's not visible on the hourly and only partially visible on the daily view.
image

I'll be taking a quick look at this later today but I'd like to get either Felix or Annas approval as well before merging this.

**Comment by t-couery** [comment]
Thx fyi I've updated my content to include more information about the changes

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Review by FelixDQ — APPROVED** [review]
Thank you @t-couery !

**Review by annaib00 — APPROVED** [review]
LGTM!

**Pull request merged**
