### PR TITLE
update(parser) - PE

### PR DESCRIPTION
**Pull request by mathilde-daugy**
## Issue

MAP_GENERATION was wrong
image

## Description

update MAP_GENERATION and migrate to new parser_validation scheme + enable historical backfill

@VIKTORVAV99 we can merge with #6481 to add the unit tests

### Preview

image

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
I think I'll merge the other PR first, then I'll fix any potential merge conflicts in here.

**Comment by mathilde-daugy** [comment]
sure, since we will enable backfilling it is not urgent

**Comment by VIKTORVAV99** [comment]
> sure, since we will enable backfilling it is not urgent

I'll take care of it today, got some stuff I need to do anyhow.

**Comment by VIKTORVAV99** [comment]
Tests are updated but I think we should get a new mock data file that represent the fact that we only do 1 API call now, I'll take care of it later today if I have the time.

**Comment by mathilde-daugy** [comment]
i've update the mock file nd the snapshot so you can review now :)

**Review by VIKTORVAV99 — COMMENTED** [review]
Just two small notes otherwise it looks good!

**Review by VIKTORVAV99 — APPROVED** [review]
Looks good to me!

Nice work!

**Pull request merged**
