### PR TITLE
HACK(EMAPSLE):opens a zone of the day

### PR DESCRIPTION
**Pull request by tonypls**
### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Oh wow ESLint really don't like this PR 😅
I however think it's a cool idea!

**Comment by tonypls** [comment]
> Oh wow ESLint really don't like this PR 😅 I however think it's a cool idea!

Play here https://e0f6f30c.electricitymaps-staging.pages.dev/DK-DK2

**Comment by VIKTORVAV99** [comment]
> > Oh wow ESLint really don't like this PR 😅 I however think it's a cool idea!
> 
> Play here https://e0f6f30c.electricitymaps-staging.pages.dev/zone/EMAPSLE?remote=true

I got an easy one!
image

**Comment by tonypls** [comment]
> > > Oh wow ESLint really don't like this PR 😅 I however think it's a cool idea!
> > 
> > 
> > Play here [e0f6f30c.electricitymaps-staging.pages.dev/zone/EMAPSLE?remote=true](https://e0f6f30c.electricitymaps-staging.pages.dev/zone/EMAPSLE?remote=true)
> 
> I got an easy one! image

You're also a pro so they're probably all easy! Everyone should get the same each day 🎉

**Comment by madsnedergaard** [comment]
This was a lot of fun! 🥳 

I suggest we close this PR again though, I don't think keeping it open is going to help us pick it up again any time soon. Feel free to open again if you disagree though :)

**Pull request closed without merging**
