### PR TITLE
Add french translations for tooltips

### PR DESCRIPTION
**Pull request by phiphou**
Add french translations for the main indicators tooltips.

I followed the English wording, so "from generating electricity" gives "issues de la production d'électricité".

But it would be cool if this tooltip text was dynamic : the term "generating" should be "production" or "consumption" depending on the app current mode.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Good call about production vs consumption!

I'll see what we can do about that, but it should be fairly easy to add.

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Comment by phiphou** [comment]
> Good call about production vs consumption!
> 
> I'll see what we can do about that, but it should be fairly easy to add.

I see two options : 

- you reuse the terms production / consumption and their translation
- we use two different keys in translation files

Not sure about what is the best choice.

**Comment by VIKTORVAV99** [comment]
> > Good call about production vs consumption!
> > I'll see what we can do about that, but it should be fairly easy to add.
> 
> I see two options :
> 
> * you reuse the terms production / consumption and their translations
> * we use two different keys in translation files
> 
> Not sure about what is the best choice.

I think the easiest might be to just do two different keys since replacing parts of it could create unexpected behavior in some languages, especially non latin ones (I think).

**Pull request merged**
