### PR TITLE
fix(parsers):Remove geothermal from NL parser

### PR DESCRIPTION
**Pull request by annaib00**
## Issue
Fix to issue #7386. Removing geothermal (type 9 in https://ned.nl/nl/handleiding-api) production from NL parser, as NL does not have any geothermal production. It is not added to unknown as we are already reporting more production than Eurostat and it could be geothermal heat production. 

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Changes look good!

However do we have a plan for removing the geothermal data from the database?

It will not get overwritten as this will now return null values (not 0).

**Comment by annaib00** [comment]
Ah, okay! No, we do not have a plan for that currently. Do you know if there are any nice way of doing this? Or should I just manually add a Geothermal value = 0 production i the parser?

**Comment by VIKTORVAV99** [comment]
> Ah, okay! No, we do not have a plan for that currently. Do you know if there are any nice way of doing this? Or should I just manually add a Geothermal value = 0 production i the parser?

I'll leave this up to @FelixDQ to decide, we have in the past been hesitant to hardcode values as it increases maintenance and risks being wrong in the future. But on the other hand I don't think the Netherlands will add geothermal electricity generation.

Otherwise you'll have to write a database migration to remove them.

**Comment by annaib00** [comment]
Okay, @FelixDQ is on vacation this week so I will look more into it when he is back :)

**Pull request merged**
