### PR TITLE
feat: add info and settings button on mobileheader

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue
Closes: AVO-368

## Description
Adds the info and settings buttons to the mobile header so they are easier to use on mobile. I also made sure they are in the exact same position as on the map so there is no CLS.

Also refractors the CSS a bit so the components are never hidden and uses conditional rendering instead to reduce the active DOM count and switches to Lucide icons.

### Preview
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-06 at 16 19 51

Simulator Screenshot - iPhone 15 Pro Max - 2024-08-06 at 16 20 06

Simulator Screenshot - iPhone 15 Pro Max - 2024-08-06 at 16 20 30

Simulator Screenshot - iPhone 15 Pro Max - 2024-08-06 at 16 20 43

### Double check

- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
I'll grab new screenshots with medium sized buttons if it's needed 👍🏻

**Comment by Alportan** [comment]
> I'll grab new screenshots with medium sized buttons if it's needed 👍🏻

No need, I'm checking the deployments usually as it's easier to see the changes in action. 💪 

Some small feedback:
1. increase we make the icon padding-top on both map and zone view from `5px` to `8px`
2. **in zone view:** reduce the padding-bottom to `0px` so we won't take additional vertical space
3. **in zone view:** remove the drop-shadow for simplicity

Let me know if you have any questions! 🙌

**Comment by VIKTORVAV99** [comment]
> > I'll grab new screenshots with medium sized buttons if it's needed 👍🏻
> 
> No need, I'm checking the deployments usually as it's easier to see the changes in action. 💪
> 
> Some small feedback:
> 
> 1. increase we make the icon padding-top on both map and zone view from `5px` to `8px`
> 2. **in zone view:** reduce the padding-bottom to `0px` so we won't take additional vertical space
> 3. **in zone view:** remove the drop-shadow for simplicity
> 
> Let me know if you have any questions! 🙌

Should the top padding also apply to the logo in the zone view (I assume yes)?

**Comment by VIKTORVAV99** [comment]
@Alportan I adjusted the styling a bit, it now has 2rem (8px) padding around the entire icons but the wrapper don't ignores pointer events (so now you can technically click between the buttons) making them feel more floating and helps centre the buttons when in the zone panel.

Let me know what you think.

**Comment by Alportan** [comment]
> @Alportan I adjusted the styling a bit, it now has 2rem (8px) padding around the entire icons but the wrapper don't ignores pointer events (so now you can technically click between the buttons) making them feel more floating and helps centre the buttons when in the zone panel.
> 
> Let me know what you think.

Looks good on my side. 🥳 🙌 It's a quick fix that we should probably prioritise getting out 💪

**Comment by Alportan** [comment]
> 
> Looks good on my side. 🥳 🙌 It's a quick fix that we should probably prioritise getting out 💪

One thing that I notices is that sometimes the historical picker disappears. Is it related to any of these changes? I'm asking as I don't see that happening in other branches 🙋 @VIKTORVAV99

**Comment by VIKTORVAV99** [comment]
> > 
> 
> > Looks good on my side. 🥳 🙌 It's a quick fix that we should probably prioritise getting out 💪
> 
> 
> 
> One thing that I notices is that sometimes the historical picker disappears. Is it related to any of these changes? I'm asking as I don't see that happening in other branches 🙋 @VIKTORVAV99 

It really shouldn't affect each other, as the code is completely unrelated.

Did you test on mobile? If so it's not a new thing at least but we don't really know why it's happening yet.

**Comment by Alportan** [comment]
> > > 
> > 
> > 
> > > Looks good on my side. 🥳 🙌 It's a quick fix that we should probably prioritise getting out 💪
> > 
> > 
> > One thing that I notices is that sometimes the historical picker disappears. Is it related to any of these changes? I'm asking as I don't see that happening in other branches 🙋 @VIKTORVAV99
> 
> It really shouldn't affect each other, as the code is completely unrelated.
> 
> Did you test on mobile? If so it's not a new thing at least but we don't really know why it's happening yet.

I tested it on Chrome and Safari, both on this branch and prod and it's there everywhere, so completely unrelated. All good on my side then, I'll review now! 🙌

**Review by Alportan — APPROVED** [review]
Looking good! 😎 Let's do this 💪

**Pull request merged**
