### PR TITLE
fix: Mexico CENACE parser

### PR DESCRIPTION
**Pull request by tuxity**
## Issue

Broken CENACE parser, not reported (it seems)

Fixes: #5393

## Description

- update URL
- dynamically load __VIEWSTATE
- fix a deprecation warning

### Preview

N/A

### Double check

- [X] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [X] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by FelixDQ** [comment]
Thank you @tuxity!

It seems like the data source geoblocks requests from Europe, so we need to use our proxy. I'll try to set it up next week.

**Comment by tuxity** [comment]
> Thank you @tuxity!
> 
> 
> 
> It seems like the data source also started geoblocking requests from Europe, so we need to use our proxy. I'll try to set it up next week.

Sure, let me know if I can do something to speed it up 👍

**Comment by FelixDQ** [comment]
I just added the URL to our proxy whitelist. Would you be able to change the parser so that it uses our US proxy? You can see how it was done for the California parser here: https://github.com/electricitymaps/electricitymaps-contrib/blob/master/parsers/US_CA.py

**Comment by tuxity** [comment]
@FelixDQ Done, but it seems from my end the URL is not correctly whitelisted
https://us-ca-proxy-jfnx5klx2a-uw.a.run.app/Paginas/SIM/Reportes/EnergiaGeneradaTipoTec.aspx?host=https://www.cenace.gob.mx%22 returns `Host https://www.cenace.gob.mx" is not allowed`

**Comment by FelixDQ** [comment]
I think that it works if you remove the %22:

https://us-ca-proxy-jfnx5klx2a-uw.a.run.app/Paginas/SIM/Reportes/EnergiaGeneradaTipoTec.aspx?host=https://www.cenace.gob.mx

**Comment by FelixDQ** [comment]
It looks like the proxy somehow returns `text/plain` instead of `application/octet-stream`. I can run the parser with a breakpoint and see the response. 

i.e. if i outcomment the following, then the parser works as expected:
```py
    if (
        "Content-Type" not in response.headers
        or response.headers["Content-Type"] != "application/octet-stream"
    ):
        raise Exception(
            f"Error while fetching csv for date {datestr}: No CSV was returned by the API. Probably the data for this date has not yet been published."
        )
```

**Comment by VIKTORVAV99** [comment]
@tuxity please do not use force-push it breaks any local copy of your branch anyone else would have.

That only makes it harder for us to review and makes it a lot harder to follow the changes in the PR.

**Comment by tuxity** [comment]
@VIKTORVAV99 I'm doing a rebase on master to avoid doing merge commits. It's a known process when working on your own branch. Why would anyone have a local copy of my branch if I'm alone working on that?

Anyway, PR is ready for review I don't plan to push more code change in this PR.

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 I'm doing a rebase on master to avoid doing merge commits and I'm not squashing commits so you can follow PRs changes. It's a known process when working on your own branch. Why would anyone have a local copy of my branch if I'm alone working on that?
> 
> Anyway, PR is ready for review I don't plan to push more code change in this PR.

How else do you expect us to test it if we don't have a local copy?

I for one have a broken local branch that can't be updated cleanly now.

Just do merge commits, they'll all be squashed when we merge to master.

**Comment by tuxity** [comment]
Isn't what Github workflows supposed to test when updating a PR? If you have to manually test each PRs every time then the processes aren't optimized at all. I will be glad to take a look at that.

**Comment by VIKTORVAV99** [comment]
> Isn't what Github workflows supposed to test when updating a PR? If you have to manually test each PRs every time then the processes aren't optimized at all. I will be glad to take a look at that.
> 
> If you want to update your local branch you can:
> ```
> git reset --hard HEAD~10
> git pull
> ```
> And I'm sure there is also a solution using rebase.
> 
> EDIT:
> Here a better way to reset your local branch:
> ```
> git fetch
> git reset --hard origin/fix_mexico_parser
> ```

Sure but the MX parser has no tests and that only test logic and don't actually make requests to the parser source.

It would be incredibly flaky if they suddenly updates the data blocking all other PR, we would have to add tokens to the workflows that would only be usable if push the branch to this repository which only members can do or use a very insecure alternative that would give anyone access to the tokens.

This is simply things we can not do as it would cause more problems than it solves.

**Comment by tuxity** [comment]
From what I saw there is definitely some improvements to be made around that. I will take a look when I can.

**Review by FelixDQ — APPROVED** [review]
LGTM! Thanks a lot for your work on fixing the parser @tuxity 

Sorry for the slow review. We had a team hackathon last week

**Pull request merged**
