### PR TITLE
bug(web): midnight line not visible on mobile devices

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
Midnight line not showing on mobile devices

## Description
This PR updates the logic for finding midnight to use the JavaScript Intl api

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Think you can throw in a fix for this in the same PR?
image

I think you just need to check that isHourly is true as well.

**Comment by tonypls** [comment]
> Think you can throw in a fix for this in the same PR? image
> 
> I think you just need to check that isHourly is true as well.

How do I replicate this? Doesn't show on 30d for me

**Comment by VIKTORVAV99** [comment]
> > Think you can throw in a fix for this in the same PR? image
> 
> > 
> 
> > I think you just need to check that isHourly is true as well.
> 
> 
> 
> How do I replicate this? Doesn't show on 30d for me

I just set it to English and it appeared, but it might be specific to US English.

I can try a few steps tomorrow if this don't work.

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
