### PR TITLE
Switch Croatia (HR) to ENTSO-E for production data. (Significantly reduces unknown data)

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
In this PR:

- Switches Croatia (HR) to the ENTSO-E parser to significantly reduce the amount of unknown production data. (Roughly from 45% to 2% at the time I'm writing this.)
- Adds ENTSO-E forecasts to generation and exchanges.
- Removes now unused `HOPS.py` parser, `test_HOPS.py` test file and files associated with the test file.

ref: #3408

### CODE REVIEW

**Comment by q--** [comment]
This was proposed earlier, see  #2885

Back then the problem was that ENTSO-E data lagged significantly compared to HOPS. I don't know if things are better now, but it's something to consider

**Comment by VIKTORVAV99** [comment]
> This was proposed earlier, see  #2885
> 
> Back then the problem was that ENTSO-E data lagged significantly compared to HOPS. I don't know if things are better now, but it's something to consider

I did a quick check before making the PR and then the data only lagged 1-2 hours so that shouldn't be a problem.

What might be a problem is they seems to report 0 production in the future and later correcting it with the correct value. For example right now it's 14:30 local time but Croatia has 0 value production for installed sources reported till midnight.

**Comment by VIKTORVAV99** [comment]
Hmm looks like the data reported to ENTSO-E is very irregular, ranging from a 1-hour to delay to a 5-hour delay at the time of writing, we might need to hold off on this PR until further notice. 😐

**Comment by VIKTORVAV99** [comment]
@Kongkille now that historical view has launched I feel like this is worth revisiting.
Do you think the additional source breakdown (and therefore more accurate co2eq/kWh) is worth the longer data delay?

**Comment by VIKTORVAV99** [comment]
@pierresegonne pinging you in here as well since I think it would be a net improvement (especially for historical data) to switch to the ENTSO-E parser for Croatia even if it has significant delays (I have observed up to 8 hours delays but could be longer) in the data and then fill the gap with a estimation model.

I'm not sure what data or how much data is needed to create a estimation model but ENTSOE-E seem to have almost full production data (no geothermal or waste) since 2019-01-01. On 2019-02-01 they added geothermal data and on 2019-07-26 they added waste data.

**Comment by Kongkille** [comment]
Hmm it's hard to factor in the value of not having real-time data tbh.

@pierresegonne let's discuss

**Comment by pierresegonne** [comment]
Hey, sorry for the delay in coming back to you guys. 

I'd say that it depends on how easily predictable the Croatian grid is.
From your experience, what have you seen @VIKTORVAV99 ? What are the main production modes? 

If there are not too many variations, then we know that the model will do an OK job at estimating the real time data, and in that case, I think the trade-off is worth it :)

**Comment by VIKTORVAV99** [comment]
> Hey, sorry for the delay in coming back to you guys. 
> 
> I'd say that it depends on how easily predictable the Croatian grid is.
> From your experience, what have you seen @VIKTORVAV99 ? What are the main production modes? 
> 
> If there are not too many variations, then we know that the model will do an OK job at estimating the real time data, and in that case, I think the trade-off is worth it :)

The main production modes seem to be:
- Biomass - pretty consistent at around 66-68mw the last few days (at least)
- Gas - ranging from 350 MW to 450MW
- Coal - 200±1MW
- Geothermal - 6±1MW
- Hydro - 50 to 500 MW
- Solar - 0 to 42MW
- Unknown - 32±1MW
- Wind - 4 to 200 MW

So everything except hydro, solar and wind seem to be pretty consistent and solar at least should be easy enough to estimate.

It also has solar and wind forecast available, is that something we use in the estimation models?

**Comment by pierresegonne** [comment]
> It also has solar and wind forecast available, is that something we use in the estimation models?

Not yet unfortunately 

---

I think the tradeoff is worth it. I'm not going to merge it straight away - as I'm still doing some post-processing following the merging of SE but will do unless @Kongkille or @tonypls or @mathilde-daugy have strong opinion against

**Comment by VIKTORVAV99** [comment]
> > It also has solar and wind forecast available, is that something we use in the estimation models?
> 
> Not yet unfortunately
> 
> I think the tradeoff is worth it. I'm not going to merge it straight away - as I'm still doing some post-processing following the merging of SE but will do unless @Kongkille or @tonypls or @mathilde-daugy have strong opinion against

I just added a small edit to my comment, please check it as it might impact this.

**Comment by VIKTORVAV99** [comment]
> > It also has solar and wind forecast available, is that something we use in the estimation models?
> 
> Not yet unfortunately
> 
> I think the tradeoff is worth it. I'm not going to merge it straight away - as I'm still doing some post-processing following the merging of SE but will do unless @Kongkille or @tonypls or @mathilde-daugy have strong opinion against

There is also a lot of conflicts and a few things have changed since I created this PR originally so even if we want to merge it I have some cleanup to do first.

**Comment by VIKTORVAV99** [comment]
Looks like the data for HR is being reported hourly now to ENTSO-E so this should have no issues being merged as the previous blockers have been resolved.

I'll fix all the merge conflicts and mark this PR as ready tomorrow (hopefully).

**Comment by VIKTORVAV99** [comment]
I'm running into some issues with lint-staged and eslint and prettier failing cause the stings are too long??? But since the actual changes are pretty small I think I'll just re-create the PR on a clean branch.

**Pull request closed without merging**
