### PR TITLE
Add some french translations

### PR DESCRIPTION
**Pull request by phiphou**
Add french translation for the new "share the app" text in left panel.

ps : I think you could add a little more space before the buttons that follw this text.

Complete #7105

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
LGMT! 🎉

I'll also make a note about the more space, but it's a balance to allow for longer feedback button strings and smaller screens.

**Comment by phiphou** [comment]
> LGMT! 🎉
> 
> I'll also make a note about the more space, but it's a balance to allow for longer feedback button strings and smaller screens.

That's a good point, my translation adds 9 characters to the english one, don't know if it will cause a UI issue...

**Comment by VIKTORVAV99** [comment]
> > LGMT! 🎉
> > I'll also make a note about the more space, but it's a balance to allow for longer feedback button strings and smaller screens.
> 
> That's a good point, my translation adds 9 characters to the english one, don't know if it will cause a UI issue...

It shouldn't but some languages can be even longer (looking at you German 👀).

**Comment by VIKTORVAV99** [comment]
Maybe I spoke too soon 😅

You can check how it looks here: https://staging.electricitymaps.com/

I'll see if we can make it a little better alignment wise but I think we might have to accept that it will be two rows?

**Comment by phiphou** [comment]
For french, I can remove 6 characters : "application" can be shortened to "appli" (like app for application).

For buttons in the "about" part, maybe we can decrease font size a little bit, no ?

**Pull request merged**
