### PR TITLE
Remap `GT->MX` to `GT->MX-OR`

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue
The exchange did not show up on the map due to a missmatch in mappings.

## Description
This PR remaps the `GT->MX` exchange to `GT->MX-OR` which should resolve the issue.
>**Note**
>This is only safe to do becasue there is only one interconnection between Mexico and Guatamala so we will always know which zones the electricity is coming from.

Closes: #2653

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@pierresegonne since all this data should aready exist in the database under the `GT->MX` "key" do you think it would be possible to just move this data to `GT->MX-OR` so we get all the historical data?

**Review by pierresegonne — APPROVED** [review]

**Comment by VIKTORVAV99** [comment]
> Can you just ping me when you merge so that I remember ?

Sure thing! 🎉

**Review by tonypls — APPROVED** [review]
👍

**Comment by VIKTORVAV99** [comment]
@pierresegonne I'm merging this now as it no longer has any conflicts with other open PRs.

**Pull request merged**
