### PR TITLE
chore: add automation for dark and light themes for brand-green

### PR DESCRIPTION
**Pull request by Alportan**
## Description

Automate brand-green to change between light and dark themes. Also replaces all old `brand-green-dark` to simply `brand-green`.

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by Alportan** [comment]
Wait, it stopped working now! 🙃

**Comment by Alportan** [comment]
Closing this as it doesn't solve the issue I initially thought it would, switching automatically the color when switching the theme 🥲

**Comment by VIKTORVAV99** [comment]
> Closing this as it doesn't solve the issue I initially thought it would, switching automatically the color when switching the theme 🥲

I'm hoping there will be a better solution in Tailwind 4 but it has not been released yet.

Otherwise I'll see if I can hack something together at one point.

**Comment by Alportan** [comment]
Yeah, we are doing something to some extent in the index.css, but if Tailwind would natively support this, it would be better 🙌 

image

**Pull request closed without merging**
