### PR TITLE
fix(capacity.py) function get_capacity_data_with_source - index error

### PR DESCRIPTION
**Pull request by mathilde-daugy**
## Issue
image

## Description

The quality pipeline failed because of an index error in the `get_capacity_data_with_source` function. The function could not extract the source from a list of dicts! 

updated `get_capacity_value_with_datetime` to return value and source (@unitrium  i guess we want to change the name of this function?)

added forgotten test

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

___

## **Type**
Bug fix, Tests

___

## **Description**
- Fixed an index error in the `get_capacity_data_with_source` function in the `capacity.py` file. The function now correctly extracts both the capacity value and its source.
- Updated the `get_capacity_value_with_datetime` function to return a tuple containing the capacity value and source. This function now also handles cases where the source is not provided in the capacity data.
- Updated the tests in `test_capacity.py` to reflect these changes. A new test `test_get_capacity_with_source` was added to verify the correct extraction of capacity data along with the source.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>capacity.py</strong><dd><code>Fix index error in capacity data extraction functions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

electricitymap/contrib/config/capacity.py
- Updated the `get_capacity_data` and `get_capacity_data_with_source` <br>  functions to return both capacity value and source.
- Modified the `get_capacity_value_with_datetime` function to return a <br>  tuple containing the capacity value and source.
- Added handling for cases where the source is not provided in the <br>  capacity data.
    </details>
  </td>
  <td><a href="https://github.com/electricitymaps/electricitymaps-contrib/pull/6424/files#diff-e0d119614381e00a09adf28aa58d7efd5c973c1292c4c1950dad33e0b81ff935">+10/-8</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_capacity.py</strong><dd><code>Update tests for capacity data extraction functions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/test_capacity.py
- Updated existing tests to reflect changes in the `get_capacity_data` <br>  function.
- Added a new test `test_get_capacity_with_source` to verify the correct <br>  extraction of capacity data along with the source.
    </details>
  </td>
  <td><a href="https://github.com/electricitymaps/electricitymaps-contrib/pull/6424/files#diff-a3b9486615b6b86146355a5901022fe919ff588b4c7f9b3fe0a50bea5520836d">+34/-7</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table><hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `describe` tool scans the PR code changes, and generates a description for the PR - title, type, summary, walkthrough and labels. The tool can be triggered [automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) every time a new PR is opened, or can be invoked manually by commenting on a PR.

When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L46) related to the describe tool (`pr_description` section), use the following template:
```
/describe --pr_description.some_config1=... --pr_description.some_config2=...
```
With a [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app), use the following template:
```
[pr_description]
some_config1=...
some_config2=...
```

<table><tr><td><details> <summary><strong> Enabling\disabling automation </strong></summary><hr>

- When you first install the app, the [default mode](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) for the describe tool is:
```
pr_commands = ["/describe --pr_description.add_original_user_description=true" 
                         "--pr_description.keep_original_user_title=true", ...]
```
meaning the `describe` tool will run automatically on every PR, will keep the original title, and will add the original user description above the generated description. 

- Markers are an alternative way to control the generated description, to give maximal control to the user. If you set:
```
pr_commands = ["/describe --pr_description.use_description_markers=true", ...]
```
the tool will replace every marker of the form `pr_agent:marker_name` in the PR description with the relevant content, where `marker_name` is one of the following:
  - `type`: the PR type.
  - `summary`: the PR summary.
  - `walkthrough`: the PR walkthrough.

Note that when markers are enabled, if the original PR description does not contain any markers, the tool will not alter the description at all.
        

</details></td></tr>

<tr><td><details> <summary><strong> Custom labels </strong></summary><hr>

The default labels of the `describe` tool are quite generic: [`Bug fix`, `Tests`, `Enhancement`, `Documentation`, `Other`].

If you specify [custom labels](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md#handle-custom-labels-from-the-repos-labels-page-gem) in the repo's labels page or via configuration file, you can get tailored labels for your use cases.
Examples for custom labels:
- `Main topic:performance` - pr_agent:The main topic of this PR is performance
- `New endpoint` - pr_agent:A new endpoint was added in this PR
- `SQL query` - pr_agent:A new SQL query was added in this PR
- `Dockerfile changes` - pr_agent:The PR contains changes in the Dockerfile
- ...

The list above is eclectic, and aims to give an idea of different possibilities. Define custom labels that are relevant for your repo and use cases.
Note that Labels are not mutually exclusive, so you can add multiple label categories.
Make sure to provide proper title, and a detailed and well-phrased description for each label, so the tool will know when to suggest it.        

</details></td></tr>

<tr><td><details> <summary><strong> Inline File Walkthrough 💎</strong></summary><hr>

For enhanced user experience, the `describe` tool can add file summaries directly to the "Files changed" tab in the PR page.
This will enable you to quickly understand the changes in each file, while reviewing the code changes (diffs).

To enable inline file summary, set `pr_description.inline_file_summary` in the configuration file, possible values are:
- `'table'`: File changes walkthrough table will be displayed on the top of the "Files changed" tab, in addition to the "Conversation" tab.
- `true`: A collapsable file comment with changes title and a changes summary for each file in the PR.
- `false` (default): File changes walkthrough will be added only to the "Conversation" tab.
<tr><td><details> <summary><strong> Utilizing extra instructions</strong></summary><hr>

The `describe` tool can be configured with extra instructions, to guide the model to a feedback tailored to the needs of your project.

Be specific, clear, and concise in the instructions. With extra instructions, you are the prompter. Notice that the general structure of the description is fixed, and cannot be changed. Extra instructions can change the content or style of each sub-section of the PR description.

Examples for extra instructions:
```
[pr_description] 
extra_instructions="""
- The PR title should be in the format: '<PR type>: <title>'
- The title should be short and concise (up to 10 words)
- ...
"""
```
Use triple quotes to write multi-line instructions. Use bullet points to make the instructions more readable.

</details></td></tr>

<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 

</details></td></tr>

</table>

See the [describe usage](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md) page for a comprehensive guide on using this tool.

</details>

### CODE REVIEW

**Review by unitrium — APPROVED** [review]

**Comment by tonypls** [comment]
> **[PR Description](https://github.com/electricitymaps/electricitymaps-contrib/pull/6424)** updated to latest commit ([a6243e6](https://github.com/electricitymaps/electricitymaps-contrib/commit/a6243e6c81b0a52b16c1a688679ab4695a947788))

It's back from the 💀 Something must've changed with their config, I'll create a PR to make sure it doesn't run automatically

**Comment by unitrium** [comment]
Didn't we agree that we were ok with to keep the PR description and make the code suggestions on demand? :)
No need to stab it twice ?

**Comment by mathilde-daugy** [comment]
> Wait a second maybe I approved too fast it seems now that the `get_capacity_value_with_datetime` function returns the same as the one with the source so what's the point of having the two ?

It does not do the same thing as `get_capacity_value_with_datetime` extract capacity from a dict or a list and does not handle the case where the capacity is a float/int. We can rewrite the code to include all of that if you think it would be more efficient

**Comment by madsnedergaard** [comment]
This is failing on CI and blocking updates, so I hope you don't mind that I revert this PR while until it's fixed :)
https://drone.electricitymaps.com/electricitymaps/electricitymaps/11346/1/4

Screenshot 2024-02-09 at 11 33 44

**Pull request merged**
