### PR TITLE
Fix localizations (russian, danish, date range formatting)

### PR DESCRIPTION
**Pull request by hybridcattt**
## Issue

Hi there 👋 I saw your callout for translations on social media, so I checked the website in russian and danish. Noticed some missing & incorrect strings. 

### Improvements to russian localization
- added most missing strings for the main sidebar and the zone panel
- fixed typos and semantically incorrect translations

### Improvements to the danish localization
- added a couple of missing strings. Would add more but not sure if you want translations from a non-native speaker, or would rather keep them in english?

### Time formatting change for the time control panel

I noticed that date ranges (such as "24 hours") look quite wrong in russian and danish, when the first letter is capitalised. 
The styling is global for all languages, so I took the liberty of changing it for all, to match the native, system-defined formatting. I think it looks better in english too. 

### Preview

Screenshot 2022-09-06 at 14 44 08
Screenshot 2022-09-06 at 14 44 22
Screenshot 2022-09-06 at 14 44 32

The three change areas come as separate commits. It's easy to revert in case you don't want the capitalization change or the danish translation fixes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@rasmusjeppsen do you have any input regarding the CSS (style) change?

I think it makes sense to let the native intl object handle capitalization since it might differ between languages.

**Comment by jarek** [comment]
I am also in favour of removing the `text-transform: capitalize` on time spans. The capitalized version looks weird in Polish. I did some testing of Intl.NumberFormat and it does capitalize when needed, for example German (where nouns are capitalized) results in "24 Stunden" also without the text-transform.

Note also that we don't use text-transform on the date field in the top right corner of that box, and that formats as expected (capitals in month names in languages that need them).

**Comment by hybridcattt** [comment]
Is there anything I can do to help move this PR forward?

**Comment by VIKTORVAV99** [comment]
> Is there anything I can do to help move this PR forward?

There was some CI issues when this PR was originally opened that seems to have put it on halt a little.
I'll see if we can get this merged sooner rather than later 🙂

**Review by tonypls — APPROVED** [review]
Looks great thanks 👍

**Comment by madsnedergaard** [comment]
Thanks for fixing this (and great to "see" you again @hybridcattt) 🙌 🥳

**Comment by hybridcattt** [comment]
@madsnedergaard happy to help ☺️

**Pull request merged**
