### PR TITLE
fix: favicon

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

Apparently our SVGs where not in sync with what they should be 👀 

## Description

Updates the favicon SVG to match what is uses elsewhere in the company.

Special thanks to Alex for providing the right assets.

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@Alportan small problem with the SVG I got, it got no padding...

Would you mind sending one with the appropriate padding like the old icons had?

**Comment by madsnedergaard** [comment]
bump @Alportan <3

**Comment by Alportan** [comment]
> @Alportan small problem with the SVG I got, it got no padding...
> Would you mind sending one with the appropriate padding like the old icons had?

Ohh no, I missed this one 🙈 

Here it is @VIKTORVAV99
fav

**Comment by VIKTORVAV99** [comment]
I kind of forgot about this PR but it should be ready for review now 🙂

**Review by madsnedergaard — APPROVED** [review]

**Pull request merged**
