### PR TITLE
speed up generate-world by skipping validation if the world file is the same as the current one

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue
No real issue but will improve DX.

## Description
Speed up the generate-world file by skipping validation if the existing world file is identical to the generated one.

- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Seems like there was no need for any hashing and I overthought the whole thing in the beginning, but this should significantly speed things up when doing local development.

**Comment by VIKTORVAV99** [comment]
Tony, would you mind giving this a look? The changes should be pretty straight forward.

**Review by tonypls — APPROVED** [review]
LGTM 🎉

**Comment by madsnedergaard** [comment]
Oh hey, didn't see this PR! I did the exact same thing in https://github.com/electricitymaps/electricitymaps-contrib/pull/5182, so we should probably not double skip the check :D 
Your solution seems simpler though, so I will update my PR to remove the check again!

**Pull request merged**
