### PR TITLE
Switches yaml package to gain 5x speed

### PR DESCRIPTION
**Pull request by madsnedergaard**
## Issue

Splitting up the config file in #5269  will be helpful in many cases, but we still often need the zones config data and that takes ~3.3s to load every single time!

## Description

To make this faster, I'm here switching from PyYAML to [ruamel.yaml](https://sourceforge.net/projects/ruamel-yaml/) in the config file. This yields a significant performance improvement from ~3.3s to ~0.6s.

I decided to leave PyYAML as we have more advanced usage in some scripts and I was not sure enough about replacing that at this point.

_I also first tried saving the combined zone configs to one file and loading that, but it was actually slower than loading every single file 😅_ 

### Preview

Before and after:

Screenshot 2023-05-07 at 21 12 33

Validated that output is the same:

Screenshot 2023-05-07 at 21 54 41

### Double check

- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Review by pierresegonne — APPROVED** [review]
Nice optimisiation!

**Comment by VIKTORVAV99** [comment]
Is it okay if I merge this real quick before there are any more conflicts?

**Comment by madsnedergaard** [comment]
> Is it okay if I merge this real quick before there are any more conflicts?

I'd like to wait until tomorrow, as I want to first release existing stuff (there's a lot!) and address this separately afterwards as it's going to touch all internal tools :)

**Comment by VIKTORVAV99** [comment]
> > Is it okay if I merge this real quick before there are any more conflicts?
> 
> I'd like to wait until tomorrow, as I want to first release existing stuff (there's a lot!) and address this separately afterwards as it's going to touch all internal tools :)

Sure thing! I'll try to not create any conflicts before then 😉

**Comment by madsnedergaard** [comment]
I'll unfortunately have to wait with merging this for the next few weeks as I'm going on vacation. And I don't want to merge this PR that requires significant internal changes the Friday before leaving 😉

**Comment by VIKTORVAV99** [comment]
> I'll unfortunately have to wait with merging this for the next few weeks as I'm going on vacation. And I don't want to merge this PR that requires significant internal changes the Friday before leaving 😉

I'll make it as a draft in the meantime then so it's not accidentally merged!

**Comment by VIKTORVAV99** [comment]
@madsnedergaard do you think we can revive this PR now or are we waiting for something?

**Pull request merged**
