### PR TITLE
Add custom install script in cypress

### PR DESCRIPTION
**Pull request by Kongkille**
Install both mockserver and web dependencies

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
can you just do a like whitespace change in a frontend file so the cypress tests run?

**Comment by VIKTORVAV99** [comment]
Looks like we can't chain commands `error Command "&&" not found.`

**Comment by VIKTORVAV99** [comment]
I would probably just add this step:
```yml
- name: Install mockserver
        run: |
          cd /mockserver
          yarn install
```
And skip the custom install script.

**Comment by Kongkille** [comment]
> Looks like we can't chain commands `error Command "&&" not found.`

Yeah, I'll just try a few things otherwise I'll disable the tests for now

**Comment by VIKTORVAV99** [comment]
Looks like the install worked but...
```
[FAILED] The Cypress App could not be downloaded.
[FAILED] 
[FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
```

**Comment by VIKTORVAV99** [comment]
oh no don't change that, it's working now 😅

**Comment by Kongkille** [comment]
Ok it looks like it is finally working! 👯

**Comment by VIKTORVAV99** [comment]
> Ok it looks like it is finally working! 👯

Yep, looks like the old one got stuck tho so I'll just cancel that.

**Comment by Kongkille** [comment]
Thanks for the assist! Hopefully this will unblock the checks for now

**Comment by VIKTORVAV99** [comment]
No problem I'm happy to help!

If nothing changes it should stay stable so no more red crosses unless they are supposed to be there!

**Pull request merged**
