### PR TITLE
Create CZ.py

### PR DESCRIPTION
**Pull request by mastrs**
Requires the zeep and xmltodict packages as dependency in order to function.

Provides (for CZ/Czechia/ČEPS area):
– 1 minute granularity for load (consumption) data
– 15 minutes granularity for production data
– 15 minutes granularity for planned&actual crossborder flows

### CODE REVIEW

**Review by VIKTORVAV99 — CHANGES_REQUESTED** [review]
Thanks for the PR! 🎉

There are some points that needs to be addressed however:

While the increased granularity is nice I'm not sure we want ti include extra dependencies since we already have a functional parser (ENTSO-E). I'll leave this one up to the Electricity Maps team though.

A few other things I noticed right away:
- The parser don't use `ParserException` for errors.
- The file don't have a file extension.
- There is a large amount of unused imports.
- The PR is missing the needed dependencies.

The three last points need to be addressed at the very least before this even gets a full review.

**Comment by meme1255** [comment]
Thanks. I've tried to create the PR via the iPhone app and apparently didn't add the .py extension during the process. I'll address the mentioned points (the error handling) and take a look at the imports. 

I may find a way how to reduce the number of dependencies required, however, the XMLs are quite annoying to use without them.

**Comment by meme1255** [comment]
> Thanks for the PR! 🎉
> 
> There are some points that needs to be addressed however:
> 
> While the increased granularity is nice I'm not sure we want ti include extra dependencies since we already have a functional parser (ENTSO-E). I'll leave this one up to the Electricity Maps team though.
> 
> A few other things I noticed right away:
> 
> * The parser don't use `ParserException` for errors.
> * The file don't have a file extension.
> * There is a large amount of unused imports.
> * The PR is missing the needed dependencies.
> 
> The last three points need to be addressed at the very least before this even gets a full review.


Just a question related to the ParserException: Is there any parser I could use as a example? I've been following the FR.py parser which doesn't use the ParserException.

**Comment by VIKTORVAV99** [comment]
> 
> 
> 
> > Thanks for the PR! 🎉
> > 
> > There are some points that needs to be addressed however:
> > 
> > While the increased granularity is nice I'm not sure we want ti include extra dependencies since we already have a functional parser (ENTSO-E). I'll leave this one up to the Electricity Maps team though.
> > 
> > A few other things I noticed right away:
> > 
> > * The parser don't use `ParserException` for errors.
> > * The file don't have a file extension.
> > * There is a large amount of unused imports.
> > * The PR is missing the needed dependencies.
> > 
> > The last three points need to be addressed at the very least before this even gets a full review.
> 
> 
> Just a question related to the ParserException: Is there any parser I could use as a example? I've been following the FR.py parser which doesn't use the ParserException.

I personally created the ES.py parser (which was based on two other parsers) that I would consider being the best example parser because of its simplicity right now. But there are a few others that use it as well.

**Comment by meme1255** [comment]
> > > Thanks for the PR! 🎉
> > > There are some points that needs to be addressed however:
> > > While the increased granularity is nice I'm not sure we want ti include extra dependencies since we already have a functional parser (ENTSO-E). I'll leave this one up to the Electricity Maps team though.
> > > A few other things I noticed right away:
> > > 
> > > * The parser don't use `ParserException` for errors.
> > > * The file don't have a file extension.
> > > * There is a large amount of unused imports.
> > > * The PR is missing the needed dependencies.
> > > 
> > > The last three points need to be addressed at the very least before this even gets a full review.
> > 
> > 
> > Just a question related to the ParserException: Is there any parser I coulrd use as a example? I've been following the FR.py parser which doesn't use the ParserException.
> 
> I personally created the ES.py parser (which was based on two other parsers) that I would consider being the best example parser because of its simplicity right now. But there are a few others that use it as well.

Thanks! I'll add them if the parser will be considered worth it even though the additional dependencies.

**Comment by VIKTORVAV99** [comment]
@pierresegonne and @FelixDQ what do you guys thing, is it worth perusing a new parser that has higher time resolution but introduces additional python dependencies? We currently use the ENTSO-E parser with 1 hour resolution.

**Comment by VIKTORVAV99** [comment]
@mathilde-daugy If you got the time could you take a look at this as well today?
There are some questions in here that should be addressed by a team member before it proceeds.

**Comment by mathilde-daugy** [comment]
We need to discuss this and we will get back to you. :)

**Comment by meme1255** [comment]
> We need to discuss this and we will get back to you. :)

One more thing: This source would allow to provide more detailed information as there are at least two sub-networks in Germany (50Hz and Tennet) which currently aren't distinguished.

**Comment by meme1255** [comment]
Have you reached any conclusion @mathilde-daugy @VIKTORVAV99 ? I probably could spent some time if the only issue are the new dependencies to figure out how to use the data without them but if you aren't interested in the data at all…? Thanks!

**Comment by VIKTORVAV99** [comment]
> Have you reached any conclusion @mathilde-daugy @VIKTORVAV99 ? I probably could spend some time if the only issue are the new dependencies to figure out how to use the data without them but if you aren't interested in the data at all…? Thanks!

If you managed to use our existing dependencies I don't think there would be an issue with merging this and use the higher (time) resolution source.

**Comment by VIKTORVAV99** [comment]
I am going to close this due to lack of activity in this PR but if you can create a parser with the existing dependencies feel free to open a new PR.

**Pull request closed without merging**
