### PR TITLE
Add snapshot test for ENTSO-E exchange functions

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

Low testing cover for the ENTSO-E parser.

## Description

This PR adds a snapshot test for the fetch_exchange and the fetch_exchange_forecast function in the ENTSO-E parser.

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
I just noticed that the formatting is way off even though ruff was run, I think this is because I disabled the lining of the test files when I added ruff to contrib.

I'll make a follow up PR to clean up all of that.

**Comment by VIKTORVAV99** [comment]
@madsnedergaard if you have the time could you give this a quick approval? It just add some tests to make sure the other PRs don't break things.

**Review by madsnedergaard — APPROVED** [review]
LGTM! :)

**Pull request merged**
