### PR TITLE
Add VN unknown emission factor

### PR DESCRIPTION
**Pull request by silimotion**
## Description

This adds the unknown emission factor for Vietnam, prerequisite to it showing on the map. I've used EMBER data and the default emission factors from the wiki.

### Double check

- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Thanks for updating the files!

**Comment by silimotion** [comment]
@VIKTORVAV99 
Is anything left?

**Comment by VIKTORVAV99** [comment]
Not sure what you mean?

**Comment by VIKTORVAV99** [comment]
If you mean to enable the estimations not really, we just need to add it to the backend config. But we are doing some db changes so not really changing those configs until that is done.

**Pull request merged**
