### PR TITLE
New Honduras parser

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Description
Adds a new production parser for Honduras (HN) that has a full production breakdown compared to the unknown data that is used today.

### Potential future improvements

- There is exchange data available so we can create a exchange parser between HU and Guatemala, HU and El Salvador and lastly HU and Nicaragua.
- There is historical data on the dashboard but I did not find the correct endpoint/param to implement it.
- Add any potential exception handling.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
> Seems to be working pretty well!
> 
> It does through a bunch of warnings when running
> 
> ```
> InsecureRequestWarning: Unverified HTTPS request is being made to host 'otr.ods.org.hn'. Adding certificate verification is strongly advised
> ```
> 
> Have you quickly checked if you can adress them?
> 
> Otherwise my comments are just for improving code readability :)

It's because of the verify=False in the get requests, it didn't work without it so unfortunately we will have to keep it like this for now.

**Review by pierresegonne — APPROVED** [review]
👏

**Comment by madsnedergaard** [comment]
Whoops, I'm just testing deployment to Cloudflare Pages here :)

**Comment by VIKTORVAV99** [comment]
> Whoops, I'm just testing deployment to Cloudflare Pages here :)

Hehe I figured as much, it seems to be building stuff forever though 😅

**Comment by madsnedergaard** [comment]
Hi, just checking in here 7 months later to show how great this new parser was 😍 

Screenshot 2023-09-14 at 15 01 09

**Comment by VIKTORVAV99** [comment]
> Hi, just checking in here 7 months later to show how great this new parser was 😍 
> 
> Screenshot 2023-09-14 at 15 01 09
> 

I don't even remember making this PR/parser. It's quite impressive you remembered to check on the results 😅😍

**Comment by madsnedergaard** [comment]
> I don't even remember making this PR/parser. It's quite impressive you remembered to check on the results 😅😍

Haha, I was just randomly clicking around and then noticed the change from all unknown to full breakdown! 😄

**Pull request merged**
