### PR TITLE
feat(web): add link to com website from header logo

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
Were a subdomain of electrictymaps.com but it's not entirely clear how to get back
## Description
Based on some feedback from GTM, it would be normal for the logo to link back to the homepage.

This PR adds the link to electricitymaps.com on the header icon that opens in a new tab

### CODE REVIEW

**Review by VIKTORVAV99 — COMMENTED** [review]
Do we want to mark it as an external link?

**Comment by tonypls** [comment]
> Do we want to mark it as an external link?

Hmm, I like the have consistency but also don't love messing with the logo. 

It seems like in general people have pointer finger on their logo and at most a small animation.

**Comment by VIKTORVAV99** [comment]
> > Do we want to mark it as an external link?
> 
> 
> 
> Hmm, I like the have consistency but also don't love messing with the logo. 
> 
> 
> 
> It seems like in general people have pointer finger on their logo and at most a small animation.

I'll let you decide, I think it's fine either way.

**Review by VIKTORVAV99 — APPROVED** [review]

**Comment by tonypls** [comment]
> > > Do we want to mark it as an external link?
> > 
> > 
> > Hmm, I like the have consistency but also don't love messing with the logo.
> > It seems like in general people have pointer finger on their logo and at most a small animation.
> 
> I'll let you decide, I think it's fine either way.

Let's put it out there and we can update it later if we think of a better implementation

**Pull request merged**
