### PR TITLE
Change update_emission_factors_sources.py and rerun

### PR DESCRIPTION
**Pull request by qyearsley**
## Description

I noticed that:

 - update_data_sources.py and update_emission_factors_sources.py were duplicates
 - Neither one reflected the current formatting of the EMISSION_FACTORS_SOURCES.md file.

Having duplicate scripts could lead to confusion if they get out of sync, so I thought it might be helpful to delete one of them.

I updated the other to have a file-level docstring and changed the formatting to match the
EMISSION_FACTORS_SOURCES.md file. After rerunning the script, there are some updates
based on updates in the zone config sources.

@pierresegonne  does this look okay?

### Double check

- [ N/A] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Comment by qyearsley** [comment]
Sounds good -- also it looks like the .md file should be formatted by prettier so that needs to be fixed.

**Comment by VIKTORVAV99** [comment]
@qyearsley please do not use force push, it makes it more or less impossible to view changes between commits in an easy way. Since we use squash merge the number of commits is not an issue so don't worry about that.

**Comment by qyearsley** [comment]
Got it -- thanks! I'm new to contributing on GitHub so I wasn't sure how to do it exactly.

**Comment by VIKTORVAV99** [comment]
> Got it -- thanks! I'm new to contributing on GitHub so I wasn't sure how to do it exactly.

We prefer small(ish) commits and merging in master to get the latest updates as review comments and such don't work well with force push (and we have to review everything again). Other repositories might do things differently though.

Nice that you decided to start working on open source projects and found us! We appreciate the effort you have put in around making our in code documentation more clear and adherent to standards (as well as removing duplicate code).

**Review by pierresegonne — COMMENTED** [review]
LGTM, good job :)

**Review by pierresegonne — APPROVED** [review]

**Pull request merged**
