### PR TITLE
Fix KR parser down (SSL certificate issues) and invert hydro storage

### LINKED ISSUE #5469: KR production parser down
## Description

This is an automatic error report generated for South Korea (KR).

Issues:
- No recent data found for `consumption` parser
- No recent data found for `price` parser
- No recent data found for `production` parser

## Suggestions
- Try running the parser locally using the command `poetry run test_parser KR production`
- <a href="https://storage.googleapis.com/electricitymap-parser-logs/KR.html">Explore the runtime logs</a>

You can see an overview of all parser issues [here](https://github.com/tmrowco/electricitymap-contrib/wiki/Parser-issues).

### PR DESCRIPTION
**Pull request by wrma6**
## Issue

Closes #5469

## Description

Fix the issue of the KR parser being down, this is the easy solution of just disabling the SSL certificate check that is failing (probably due to the fact that the Python requests library doesn't recognize the site's signing authority).

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Review by unitrium — APPROVED** [review]
Looks good to me!

**Comment by VIKTORVAV99** [comment]
Nothing related to this PR on it's own but should the hydro storage values not be inverted?

**Comment by wrma6** [comment]
Yeah, I think the hydro storage value should be inverted, should I add that in to this PR?

**Comment by VIKTORVAV99** [comment]
> Yeah, I think the hydro storage value should be inverted, should I add that in to this PR?

Yeah you can do it in this PR.

It's a little bit confusing but discharge (production) should be negative and charging should be positive.

**Pull request merged**
