### PR TITLE
Change all current log messages to info, warn or error

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
Changes all current log messages to info, warn or error and adds info to allowed console functions.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@madsnedergaard is there some particular reason we only run eslint on these files instead of everything?
```
eslint geo src --ext .js,.jsx
```

We could just do this if there is no particular reason:
```
eslint .
```

Because right now eslint miss some of the files both in the CI and running `yarn run lint`.

**Comment by madsnedergaard** [comment]
> @madsnedergaard is there some particular reason we only run eslint on these files instead of everything?
> 
> ```
> eslint geo src --ext .js,.jsx
> ```
> 
> We could just do this if there is no particular reason:
> 
> ```
> eslint .
> ```
> 
> Because right now eslint miss some of the files both in the CI and running `yarn run lint`.

Good question, I can't remember why it was done like that 🤔 Maybe it's faster because it's skipping some folders/files? If it's not, then let's just change it :D

**Review by madsnedergaard — APPROVED** [review]
LGTM!

**Comment by VIKTORVAV99** [comment]
> > @madsnedergaard is there some particular reason we only run eslint on these files instead of everything?
> > ```
> > eslint geo src --ext .js,.jsx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We could just do this if there is no particular reason:
> > ```
> > eslint .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Because right now eslint miss some of the files both in the CI and running `yarn run lint`.
> 
> Good question, I can't remember why it was done like that 🤔 Maybe it's faster because it's skipping some folders/files? If it's not, then let's just change it :D

Since I added caches to eslint a while ago it should just be a matter of milliseconds 😅
I'll change it and then get this merged.

**Pull request merged**
