### PR TITLE
chore(DO): update parser

### PR DESCRIPTION
**Pull request by pierresegonne**
## Issue

The `DO` parser is reporting `NaN` values for solar instead of 0. These values corrupt the backend.

## Description

* Simplify the data processing
* Adopt parser validation for parser
* Adopt a mechanism to correct the NaN values which are supposed to be 0s.

@VIKTORVAV99 can you follow up with a PR on the parser validation that sets `NaN` values to `None`? 

### Preview

With this example, you can see that we just started receiving solar production for the latest hour, it set the rest of the values to 0. 

Screenshot 2024-04-18 at 13 03 57

(It was reporting NaN just a few minutes ago)

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
I'll take a deeper look at this once I get back from school and add some additional testing to ensure all the NaN cases are caught.

**Comment by pierresegonne** [comment]
> I'll take a deeper look at this once I get back from school and add some additional testing to ensure all the NaN cases are caught.

Great thanks! It's not urgent urgent btw, I'll fix the issue on the back end side now

**Comment by VIKTORVAV99** [comment]
Since this is not super urgent I'll try and add a snapshot test showcasing the issue and double check that the (production) values are corrected with the data that is returned.

**Comment by VIKTORVAV99** [comment]
Turns out the fix was pretty small for the NaN values and just needed to be "moved up" one level to fix it so I hope you don't mind I added it here directly.

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM!

If you rather want me to add a new PR for the event fixes let me know 🙂

**Comment by pierresegonne** [comment]
All good!

**Pull request merged**
