### PR TITLE
feat(config): re-enable price for nordpool zones

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
We had to remove price data for Nordpool zones!

## Description
This PR removes the filtering flags for price data that we previously didn't have the licensing to share. We've now purchased the license and can re-enable this feature 🎉

### CODE REVIEW

**Review by VIKTORVAV99 — COMMENTED** [review]
Do you know if we also have to change the source values or is it enough that we have the license?

**Comment by madsnedergaard** [comment]
Should we coordinate some SoMe content when releasing this? :)

**Comment by tonypls** [comment]
> Do you know if we also have to change the source values or is it enough that we have the license?

Good question, I think the source is still ENTSOE but the source of the source is Nordpool. It's probably better to use Nordpool 🤔

**Comment by tonypls** [comment]
> Should we coordinate some SoMe content when releasing this? :)

Good idea! We might be able to turn around some negative app reviews too. I've made issues here AVO-374 AVO-375

**Comment by VIKTORVAV99** [comment]
> > Do you know if we also have to change the source values or is it enough that we have the license?
> 
> 
> 
> Good question, I think the source is still ENTSOE but the source of the source is Nordpool. It's probably better to use Nordpool 🤔 

We don't actually say the source for the price data in the app yet so I guess we could either skip it or hardcode it for now.

I think the ENTSO-E license also allows us to use it as long as we have the Nordpool license as well.

**Review by VIKTORVAV99 — APPROVED** [review]

**Pull request merged**
