### PR TITLE
close dropdown on outside click

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
Mobile issue where closing the modal while a dropdown menu was open left the app in a frozen state

## Description
Using multiple radix components with portals can cause strange interactions, the outside click for the modal didn't properly close the portal for the dropdown menu leaving the pointer-events: none state on the body element. 

The fix to this was to specify modal={false} in the child portal, in this case the dropdown menu.

Also added closing of the dropdown menu when a value is selected.

### CODE REVIEW

**Review by madsnedergaard — APPROVED** [review]
Oh, good catch! And a bit annoying that the now have to "manage" state that radix should be fully handling, but oh well ¯\\\_(ツ)\_/¯

**Comment by tonypls** [comment]
> Oh, good catch! And a bit annoying that the now have to "manage" state that radix should be fully handling, but oh well ¯\_(ツ)_/¯

I found a slack overflow that mentioned using triggers correctly for dialogue components, I tried this and it didn't solve this issue. In the future switching all our modals to use trigger components could be a nice way to tidy things a little.

**Comment by VIKTORVAV99** [comment]
Hehe it looks like the component tests you added are doing what they should 😅

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
