### PR TITLE
fix(Wind & Solar layers): use v8 GFS endpoint

### LINKED ISSUE #6683: Wind layer not working anymore
I love your page/information. I noticed that since a couple days the "wind indiicator" (indicating the wind streams) does not work anymore on my display. Do you have any idea what the cause might be ? Thanks and regards
albert

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

The old v3 endpoint could not handle the changes made for facilitate the cache busting in v8.

Fixes #6683 

## Description

This PR switches the frontend to use the v8 GFS endpoint.

>[!IMPORTANT]
> This requires a backend PR to be merged first for solar to work.

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
In draft so it's not accidentally merged, but it's ready for review.

**Comment by tonypls** [comment]
Looks good, will approve when I can test the branch against the deployed back-end changes 👍

**Comment by VIKTORVAV99** [comment]
> Looks good, will approve when I can test the branch against the deployed back-end changes 👍 

Should be working now 🙂

**Comment by tonypls** [comment]
> > Looks good, will approve when I can test the branch against the deployed back-end changes 👍
> 
> Should be working now 🙂

Wow, I'm impressed how far our CI has come to deploy that quickly 🙌

**Review by tonypls — APPROVED** [review]
LGTM

**Pull request merged**
