### PR TITLE
Update minimal Slovenian production to just 140MW

### PR DESCRIPTION
**Pull request by DavidKarlas**
## Issue
Slovenia doesn't have data for most of October.

## Description
In April I reduced minimal production to 800MW see PR: https://github.com/electricitymaps/electricitymaps-contrib/pull/4043 But with Nuclear power plant in maintenance for a month of October, TEŠ was supposed to work whole month but TEŠ has problems with coal production, hence it shut down as well to build up coal storage for winter months, hence Slovenia can sometimes produce only 145MW(according to logs) its mostly just rivers at night and those conserve water for morning/evenings...

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Checks out so this PR LGTM! 🎉

**Comment by DavidKarlas** [comment]
Hi, any idea when this is getting deployed?

**Comment by VIKTORVAV99** [comment]
Should be any day now.
But we need @pierresegonne or @mathilde-daugy help with re-fetching the missing data for October.

**Comment by mathilde-daugy** [comment]
> Should be any day now. But we need @pierresegonne or @mathilde-daugy help with re-fetching the missing data for October.

We're currently re-fetching data for the US and should be able to get this data after. I think it'll be done wednesday :)

**Pull request merged**
