### PR TITLE
DE capacity - add geothermal

### PR DESCRIPTION
**Pull request by mathilde-daugy**
according to ENTSOe there is geothermal production in DE and we don't want to flag all datapoints

https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2016+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2024+00:00|UTC|YEAR&area.values=CTY|10Y1001A1001A83F!BZN|10Y1001A1001A82H&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19

### CODE REVIEW

**Review by unitrium — APPROVED** [review]

**Comment by unitrium** [comment]
So we get to our first config were we mix two datasources, didn't take very long 😅

**Comment by VIKTORVAV99** [comment]
Just curious here, why are we not using ENTSO-E for all the capacity data?

**Comment by mathilde-daugy** [comment]
We do not get battery storage data from ENTSOe and even though our parser doesn't collect that information it is interesting to see the evolution

**Comment by VIKTORVAV99** [comment]
> We do not get battery storage data from ENTSOe and even though our parser doesn't collect that information it is interesting to see the evolution 

Hopefully they'll add that soon, which I've been told they want to do. Then we should get both capacity and storage values for it.

**Pull request merged**
