### PR TITLE
Align CSS breakpoints

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
Fixes: #4441

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@tonypls this works for me locally but the code doesn't scale very well when resizing windows in the dev console, so I had some trouble testing it. So please double check so everything works as expected when running it locally.

**Comment by tonypls** [comment]
Hey Viktor excuse the lack of action on this PR, I think it would be good to have a helper or function to reliably determine if mobile or desktop. 

I feel like when we're checking .1 of a px it's a bit of a code smell where we should consider a more robust way to solve this problem across devices / browsers.

**Comment by VIKTORVAV99** [comment]
> Hey Viktor excuse the lack of action on this PR, I think it would be good to have a helper or function to reliably determine if mobile or desktop.
> 
> I feel like when we're checking .1 of a px it's a bit of a code smell where we should consider a more robust way to solve this problem across devices / browsers.

I agree and this was mostly a "hotfix" on my side due to lack of time (and focus on other things) hopefully we can bring a more robust system in place in the future. If you want to close this PR and wait for said more robust system I completely understand but it's up to you and the rest of the team.

**Comment by VIKTORVAV99** [comment]
The issue seems to have resolved itself (for some unknown reason?). So I'll close this PR.

**Pull request closed without merging**
