### PR TITLE
parsers:Change NL parser to only receive NED data

### PR DESCRIPTION
**Pull request by annaib00**
## Issue
NL parser to only receive NED data

## Description
Change parser to only get data from NED and not both NED and ENTSOE. 

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by DutchPower24** [comment]
License issue solved?

**Comment by VIKTORVAV99** [comment]
> License issue solved?

Yep 🙌🏻

**Comment by DutchPower24** [comment]
> > License issue solved?
> 
> Yep 🙌🏻

That is really really awesome. Will save many annoying discussions in the Netherlands. 

Thank for the good work!

**Comment by FelixDQ** [comment]
Update: We are still awaiting final approval from ned.nl before merging this. We that we'll be able to merge this soon :-)

**Comment by rpesl** [comment]
Hi, I was wondering how you selected the data sources. For example, when considering wind, you choose types 1 (Wind) and 51 (WindOffshoreC). What is the reason for not including 17 (WindOffshore) and 22 (WindOffshoreB)? Is there any documentation on how these types work together?

**Comment by VIKTORVAV99** [comment]
> Hi, I was wondering how you selected the data sources. For example, when considering wind, you choose types 1 (Wind) and 51 (WindOffshoreC). What is the reason for not including 17 (WindOffshore) and 22 (WindOffshoreB)? Is there any documentation on how these types work together?

Hi! 

There is documentation on the https://NED.nl website but the simple explanation that WindOffshoreB supersedes WindOffshore and WindOffshoreC supersedes WindOffshoreB.

**Pull request merged**
