### PR TITLE
chore(web): set CSP headers in a single place

### PR DESCRIPTION
**Pull request by jbdietrich**
## Description

Follow-up to https://github.com/electricitymaps/electricitymaps-contrib/pull/7551

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by jbdietrich** [comment]
It doesn't seem like the headers are actually added in the response 🤔

**Review by silkeholmebonnen — APPROVED** [review]
LGTM 🎅

**Comment by silkeholmebonnen** [comment]
> It doesn't seem like the headers are actually added in the response 🤔

Didn't see this comment until after I approved 😮

**Comment by VIKTORVAV99** [comment]
> It doesn't seem like the headers are actually added in the response 🤔

I think they might need to be declared one by one?

**Comment by jbdietrich** [comment]
Closing because this isn't a priority right now.

**Pull request closed without merging**
