### PR TITLE
bug(web): present electric net exchange chart for 30d+ views

### LINKED ISSUE #7593: Electric net exchange chart is only presented for 24h and 72h - not for 30d, 12mo, all
## Bug description

Data (`totalExport` and `totalImport`) is available for an electric net exchange chart with 30d+ views, but it's only presented for the 24h and 72h views.

There isn't data about `totalCo2Export` or `totalCo2Import`, so this issue is down-scoped to getting the electric net exchange chart to avoid addressing separate underlying problems. I've opened #7596 to address that.

<details><summary>Click to expand electric net exchange chart screenshots</summary>

72h view | all view (with bug fixed)
-|-
image|image

</details>

## Analysis

The reason for 30d+ views not presenting the net exchange chart stems from a detail in a low-level helper function called `getNetExchange`. Specifically its the conditional `Object.keys(zoneData.exchange).length === 0` from this code block:

https://github.com/electricitymaps/electricitymaps-contrib/blob/c9a3a8f6cd4824b80d80ba4c513f61a3ba7f9f4b/web/src/utils/helpers.ts#L190-L201

By removing it, the bug resolves.

## Why it's a bug

I consider it a bug currently because...

1. The function's name, `getNetExchange`, is a low-level helper function for getting a net exchange value from `totalImport` and `totalExport` (and CO2 equivalent values). Thus, it is surprising that it requires data about individual exchanges not used in its calculation.
2. The function `getNetExchange` is only used by the net exchange graph UI, which only affects that. The only outcome of the if statement is that the 30d+ views won't present the electric net exchange chart.

   <details><summary>Click to expand a screenshot from a repo search for the function name</summary>

   image

   </details>

### PR DESCRIPTION
**Pull request by consideRatio**
## Issue

Fixes #7593 - the issue includes an analysis and details on why this is reasonable to consider a bug fix.

## Description

The net exchange chart wasn't presented for the 30d, 12mo, and all views.

### Preview

image

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Thanks for the PR @consideRatio!

Just a heads up that we just entered a code freeze so even if this is merged we won't be deploying new code until January.

@tonypls do you remember why we did this in the first place?

**Comment by consideRatio** [comment]
@VIKTORVAV99 thank you for the quick response! I've updated the title of this PR and the linked issue to be about the _electric_ net exchange chart, because the emission net exchange chart is still not showing up for another reason - now tracked by #7596.

**Comment by tonypls** [comment]
> Thanks for the PR @consideRatio!
> 
> Just a heads up that we just entered a code freeze so even if this is merged we won't be deploying new code until January.
> 
> @tonypls do you remember why we did this in the first place?

Mostly to reduce the chance our Christmas celebrations are effected by production incidents.

This will be deployed to staging.electricitymaps.com once merged! 🚀

**Comment by VIKTORVAV99** [comment]
> > Thanks for the PR @consideRatio!
> 
> > 
> 
> > Just a heads up that we just entered a code freeze so even if this is merged we won't be deploying new code until January.
> 
> > 
> 
> > @tonypls do you remember why we did this in the first place?
> 
> 
> 
> Mostly to reduce the chance our Christmas celebrations are effected by production incidents.
> 
> 
> 
> This will be deployed to staging.electricitymaps.com once merged! 🚀 

Not the code freeze 😅

Why we added the check that blocks the net exchange graph from the daily, monthly and yearly views?

**Comment by tonypls** [comment]
> > > Thanks for the PR @consideRatio!
> > 
> > 
> > > 
> > 
> > 
> > > Just a heads up that we just entered a code freeze so even if this is merged we won't be deploying new code until January.
> > 
> > 
> > > 
> > 
> > 
> > > @tonypls do you remember why we did this in the first place?
> > 
> > 
> > Mostly to reduce the chance our Christmas celebrations are effected by production incidents.
> > This will be deployed to staging.electricitymaps.com once merged! 🚀
> 
> Not the code freeze 😅
> 
> Why we added the check that blocks the net exchange graph from the daily, monthly and yearly views?

Ah 😅 . I think because we don't show aggregate exchanges it didn't feel like the ideal solution but I guess because it's a net exchange it should be fine!

**Review by VIKTORVAV99 — APPROVED** [review]
Tested locally and it works as expected so LGTM! 🎉

Thanks for opening the PR!

**Comment by consideRatio** [comment]
Thanks for the review efforts @VIKTORVAV99 and @tonypls, excited that a small fix like this enabled me to use the aggregated net exchange view which i find very interesting!

I want politicians to value low-carbon electricity exports, and not reason "but we'll manage with one less nuclear power plant or wind park" and instead value the climate impact abroad.

**Comment by VIKTORVAV99** [comment]
> Thanks for the review efforts @VIKTORVAV99 and @tonypls, excited that a small fix like this enabled me to use the aggregated net exchange view which i find very interesting!
> 
> I want politicians to value low-carbon electricity exports, and not reason "but we'll manage with one less nuclear power plant or wind park" and instead value the climate impact abroad.
> 
> A view like this can help towards such insights i think!

No problem at all and thanks for opening the PR!

I will look into the emissions part as well (in your other issue) in the when the code freeze is over in early Jan!

Thanks again!

**Pull request merged**
