### PR TITLE
created Contributor Code of Conduct

### PR DESCRIPTION
**Pull request by fitzpaca**
## Issue
We do not have a Code of Conduct (as far as I know).

## Description

I have created a Contributor Code of Conduct for our community. My writing was inspired by [the Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/). 

The document also includes a [Conduct Violations Reporting Form](https://docs.google.com/forms/d/1B1hRzmUxGI2YDdFyv5NbHSw6vAycrgswwqEG0WCgKlM) (Google Form) for reporting violations. I am currently the owner of this form and am ready to give up ownership to the team leaders.

### CODE REVIEW

**Review by VIKTORVAV99 — COMMENTED** [review]
Great initiative!
Is there any reason this isn't using the contributor covenant directly instead of trying to make a custom version of it?

**Comment by fitzpaca** [comment]
As a student taking a class in open source development, I was required to produce original work! I would also be happy with adopting the Contributor Covenant itself.

**Comment by VIKTORVAV99** [comment]
> As a student taking a class in open source development, I was required to produce original work! I would also be happy with adopting the Contributor Covenant itself.

I see. I think we should go with an established framework but let's see what @madsnedergaard thinks.

**Comment by madsnedergaard** [comment]
I agree with @VIKTORVAV99 on this :) 
And I also think it's simpler to use `app@electricitymaps.com` as contact approach for violations instead of the form, even though it's very nice of you to set it up! 
(If that means your work here no longer qualifies for your course, then we can keep the form and transfer ownership)

**Comment by VIKTORVAV99** [comment]
@fitzpaca it would be great if you could change this to the Contributor Covenant and use the `app@electricitymaps.com` email Mads provided. 

With that being said, if this change means your course requirements are no longer being met we do have a few issues labeled with "good first issue" and "help wanted", these issues have a lower barrier of entry than the others and are often left open (for a small period) intentionally to let new contributors get familiar with the codebase in a easy way.

One of those might be able to satisfy your course requirements if this PR don't (after the change), if not I'm sure we can find something together that does. 🙂

If there is any questions regarding any of the issues I mentioned feel free to ping me and I'll provide as much context I can regarding said issue.

**Comment by fitzpaca** [comment]
In terms of course requirements, I just had to submit original work for a PR to a working open-source project (Done!). 

For the sake of Electricity Maps, let's move forward with the Contributor's Covenant as the official code of conduct. I agree that their standardized code of conduct is more appropriate for a project of this size (and caliber!) than my writing.

If we are ok with it, I am going to leave the PR as it stands until ~Dec 9th for grading purposes. Then I will follow up with the Contributor's Covenant changes to this PR.   

Thanks for being so responsive and helpful! This project has been a great first exposure to larger OSS projects.

**Comment by VIKTORVAV99** [comment]
Leaving this open until your course is graded is perfectly fine. 👍🏻

Good luck with the course!

**Comment by VIKTORVAV99** [comment]
Hey @fitzpaca I was just wondering what the status is here and if the it has been graded or not yet?

Would be really nice to get a code of conduct merged in soon!

**Comment by VIKTORVAV99** [comment]
Hello again @fitzpaca, how are things going with this PR?

**Comment by VIKTORVAV99** [comment]
This PR is now closed as we have added our own code of conduct. I hope things went well for your class and that this don't cause any problems.

**Pull request closed without merging**
