### PR TITLE
Update Norway capacities

### PR DESCRIPTION
**Pull request by nicolasca**
## Issue
Link issue: https://github.com/electricitymaps/electricitymaps-contrib/issues/4701

## Description

Update with the new hydro and wind capacities in Norway

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
There is a small diff between the total installed wind for NO and the sum of wind between the NO subzones so it seems like there is 17 MW of missing wind somewhere. Maybe you could help shed some light on it @Gazer75?

I'll approve it for the hacktoberfest credit as this is not a blocker but it should not be merged just yet.

**Comment by Gazer75** [comment]
Wind have been updated again since my last check btw. Looks like Øyfjellet is now completed and at 400 MW.

Totall now is 5056 MW
NO1 385 MW
NO2 1427 MW
NO3 2112 MW
NO4 1132 MW

If my math is not to bad that total should be accurate. There might have been some errors in the table at https://www.nve.no/energi/energisystem/vindkraft/vindkraftdata/ last time I checked, Not sure how though.

**Comment by VIKTORVAV99** [comment]
It would be great if you could update the PR with the new numbers @nicolasca. Then it should be all good to merge.

**Comment by nicolasca** [comment]
Sure I will do that today ;)

**Comment by nicolasca** [comment]
It's updated. For my knowledge, how did you find these values in the link you sent ? (I can see the overall number 5056 MW, but not the details for each zone)

**Comment by VIKTORVAV99** [comment]
> It's updated. For my knowledge, how did you find these values in the link you sent ? (I can see the overall number 5056 MW, but not the details for each zone)

In the PowerBI graph you can select "prisområde" which means bidding area (which the electricity maps zones are in this case) and see the individual total for each area.

Thanks for the update, I'll do a quick final review and merge this shortly.

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

**Comment by VIKTORVAV99** [comment]
Thanks for the help and congrats on getting your first PR merged at Electricity Maps! 🎉

**Pull request merged**
