### PR TITLE
chore: Merge GR zones

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

Closes: #6592

## Description

Previously these islands where not connected to the mainland grid but this has since changed with high voltage AC and DC power lines and the zones should now be merged.

ENTSO-E has also signaled that the production these islands will be included in the Greece production values.

### Preview
image

### Double check
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Comment by silimotion** [comment]
Two things:

- As the islands have been recently connected, shouldn't they show divided in the historical view?
- Does the capacity data available in entsoe reflect the recent changes in topology?

Thanks!

**Comment by VIKTORVAV99** [comment]
> Two things:
> 
> 
> 
> - As the islands have been recently connected, shouldn't they show divided in the historical view?
> 
> - Does the capacity data available in entsoe reflect the recent changes in topology?
> 
> 
> 
> Thanks!

For the first one:
There is a two part problem here, firstly we don't have the technical capacity to do this right now simply because the map is a static configuration. This might change in the future.

Secondly, which is a bigger problem imo as it's outside of our control is simply when they started reporting the combined values. As far as I know we where just previously operating on the assumption that the grids are separated and therefore exchange values can't affect the islands, but seemingly there is nothing blocking the TSO from reporting the production itself as part of Greece so it might be more accurate to include it in the historical view in any case.

Happy to discuss this further.

As for capacity, ENTSO-E only has yearly values so it might not reflect that until we have 2025 values for Greece, but once we do it should be available. But I can double check with ENTSO-E just to be sure.

As a note I did not see any sudden increase in production capacity between 2023 and 2024.

Depending on the generator sizes it might not be a legal requirement to include these either.

**Review by tonypls — APPROVED** [review]
LGTM, do we also want to remove all the translations for GR-IS? 

Would also be nice to link any relevant announcements / articles about the connections to the mainland in this PR as a future reference

**Comment by VIKTORVAV99** [comment]
> LGTM, do we also want to remove all the translations for GR-IS?
> 
> Would also be nice to link any relevant announcements / articles about the connections to the mainland in this PR as a future reference

Will do a quick removal of the translations 👍🏻

And then update the PR with relevant links.

**Pull request merged**
