### PR TITLE
AVO-588: Match share/copy icon to functionality

### PR DESCRIPTION
**Pull request by cadeban**
## Description
[AVO-588](https://linear.app/electricitymaps/issue/AVO-588/change-share-button-to-copy-button-when-on-desktop): Match share/copy icon to functionality

### Preview
Desktop:
Screenshot 2024-10-14 at 13 11 54

Android:
Screenshot 2024-10-14 at 13 12 23

iPhone:
Screenshot 2024-10-14 at 13 12 11

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

Is the plan still to make our own share menu later on? Utilizing our X, Linkedin, Facebook and maybe Reddit buttons?

**Comment by cadeban** [comment]
@VIKTORVAV99 Thanks for the speedy review!

I think we still plan on adding the share menu at some point, but right now it's not planned for this cycle since we have all of these other items that seem to have greater value add for storytelling in the app

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 Thanks for the speedy review!
> 
> 
> 
> I think we still plan on adding the share menu at some point, but right now it's not planned for this cycle since we have all of these other items that seem to have greater value add for storytelling in the app

Great then we are on the same page! 🚀

**Review by tonypls — APPROVED** [review]
Nice! LGTM 🎉

**Comment by cadeban** [comment]
@VIKTORVAV99 Quick update: after some discussion with Oli, this button in the zone header might be duplicative if use permalinks to the charts instead

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 Quick update: after some discussion with Oli, this button in the zone header might be duplicative if use permalinks to the charts instead

Not sure I agree on that, there should probably be a way to share the entire zone as well, but perhaps it don't need to be the green pop version.

**Pull request merged**
