### PR TITLE
fix: use id prop for Sentry instead of custom prop

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue

It seems like our custom prop is just added as additional info and is not used to detect unique users.

## Description

Uses the reserved id prop instead. This should hopefully fix the issue.

### Double check

- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Review by madsnedergaard — APPROVED** [review]
Did you test this locally? Might be the fastest way to see if it works :)

**Comment by VIKTORVAV99** [comment]
> Did you test this locally? Might be the fastest way to see if it works :)

You mean by creating a release and deliberately breaking things?

I did not but I can...

**Comment by VIKTORVAV99** [comment]
Oh that's simpler. 

I'll be away from the computer for a while but I'll do that when I get back.

**Comment by VIKTORVAV99** [comment]
So I tried testing it. And while I get the Sentry error prompt and can provide feedback it's not showing up in sentry...

Are we filtering events based on URL or similar?

**Comment by VIKTORVAV99** [comment]
Got it to work in staging and it's working as expected!

**Pull request merged**
