### PR TITLE
Update US-NW-PSEI.yaml to match 2023 Puget Sound Energy mix/capacity per reports

### PR DESCRIPTION
**Pull request by miniksa**
## Issue

I noticed that the PSE energy mix for US-WA-PSEI doesn't seem to match what is stated on PSE's website.

## Description

Update the US-NW-PSEI capacity and energy mix with information derived from PSE's official reporting at https://www.pse.com/en/pages/energy-supply/electric-supply and https://www.pse.com/en/IRP/Past-IRPs/2023-IRP

### Preview

I'm not sure how to do this as it's a configuration change that just adjusts the balance/mix.

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Thanks for updating these!

**Comment by miniksa** [comment]
Yes sorry I completely forgot I did this until recently. I'll merge it up and ping.

**Comment by miniksa** [comment]
@VIKTORVAV99, sorry for spacing out. I've merged the changes in with the new format for configs.

**Comment by miniksa** [comment]
@VIKTORVAV99, anything I can do to help get this merged? I keep checking back every week or two so I'm not holding it up this time. :)

**Comment by VIKTORVAV99** [comment]
Ah I must just have missed that this was updated, sorry about that!

In the future it helps me a lot if you re-request a review then it shows up in my normal workflows again. I'll double check this later today and if all looks good I'll merge it.

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

Sorry for it taking so long.

Do you know when the 2024 numbers are released?
Seems like solar and wind has increased a lot at least.

**Comment by miniksa** [comment]
@VIKTORVAV99, it looks like PSE does this every-other-year with the Washington State Utility Commission.

https://www.pse.com/en/IRP/Current-IRP-Process says they're working on the 2025 IRP right now which will include the updated details.

**Pull request merged**
