### PR TITLE
Update production parser delay thresholds

### PR DESCRIPTION
**Pull request by florianscheidl**
## Issue

For our alerting, we use zone-wise delay thresholds for their respective production parsers. However, for several zones, we have not computed this and therefore it does not appear in the zone config yet.

## Description

In this PR, we add computed production parser delay thresholds for all zones.

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

Just curious how this is calculated though, like why is Norway at 7 hours delay when the expected delay from ENTSO-E is 2 hours?

**Comment by florianscheidl** [comment]
It's something we are fine-tuning at the moment. I'm using a 0.75-quantile of measured delays and adding a 5-hour offset to ensure we don't get alerted right away for zones that once have a slightly greater-than usual delay.

**Comment by VIKTORVAV99** [comment]
> It's something we are fine-tuning at the moment. I'm using a 0.75-quantile of measured delays and adding a 5-hour offset to ensure we don't get alerted right away for zones that have a slightly greater-than usual delay.

Sounds great!

However I'm wondering if it doesn't make more sense to just keep the offset in the function that alerts us rather than inside the config themselves? But that's just a minor implementation detail really.

**Comment by florianscheidl** [comment]
Good point, we might want to move towards that in the future 👍

**Pull request merged**
