### PR TITLE
Revert "chore(deps): bump jotai from 2.9.3 to 2.10.1 in /web"

### PR DESCRIPTION
**Pull request by tonypls**
Reverts electricitymaps/electricitymaps-contrib#7380

Fixes AVO-635

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Should we report the behavioral change to Jotai?

**Comment by tonypls** [comment]
> > Should we report the behavioral change to Jotai?
> 
> I would if I could tell exactly why but I don't have the time to spend debugging right now

Hmm doesn't actually fix it 😢

**Comment by VIKTORVAV99** [comment]
So are we keeping the old version?

I can try and take a look at it in a bit and see if there is anything else that might have affected this.

**Comment by tonypls** [comment]
Doesn't solve the problem

**Pull request closed without merging**
