### PR TITLE
feat(translations): Auto-translate all missing Dutch keys

### PR DESCRIPTION
**Pull request by madsnedergaard**
## Description

Adds all missing keys and translates them with Claude/ChatGPT.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Now, how do I request Josee for a review...

**Comment by madsnedergaard** [comment]
> Now, how do I request Josee for a review...

On it!

**Comment by madsnedergaard** [comment]
Thanks for taking it further @VIKTORVAV99  ❤️

**Comment by VIKTORVAV99** [comment]
@madsnedergaard I'll go ahead and merge this and if Josee has any other changes or suggestions I'll open a new PR for them.

**Pull request merged**
