### PR TITLE
Aggregate USA

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
There are still some things left to do in here but the basics are there.
Left to do:
- [x] Sum all capacities
- [ ] Add translations / language strings
- [x] Add country level exchanges
- [ ] Figure out what to do with `US-SW-DEAA` 
- [x] Figure out what to do with `US-NW-SCL`
- [ ] Figure out what to do with `US-NW-AVRN`

>**Note**
>There is 75 US zones by my count and this just aggregates the 72 vissible ones on the map as adding zones without any gemoetries is currently not possible.

>**Warning**
>This should not be merged until #4677 is resolved.

### CODE REVIEW

**Comment by madsnedergaard** [comment]
FYI: We'll need to (and have planned to) verify the data internally before aggregating the US, but once that is done this is great! 🙌

**Comment by VIKTORVAV99** [comment]
> FYI: We'll need to (and have planned to) verify the data internally before aggregating the US, but once that is done this is great! 🙌

Completely understand and I have already talked a little about it with Tony and we found a few issues that might delay this a little. But the goal here is more to have all the frontend work done so you guys can just press merge once the data validation and backend is ready.

**Comment by VIKTORVAV99** [comment]
@tonypls while this isn't ready yet and have to wait for #4677 do you have any ideas what we should do with the zones US-SW-DEAA, US-NW-SCL and US-NW-AVRN? They have capacities and parsers but no geometries so they can't be included in the subZones right now.

I see a few solutions to this:
1. Create gemoetries for them.
2. allow zones with no geometries to be included in subzones and modify all related scripts/jobs.
3. Remove them.
4. Combine them with other zones.

**Comment by unitrium** [comment]
@VIKTORVAV99, we're consolidating the missing parts on our backend before being able to roll out the US aggregation.
We are going to combine and clean some of the US you mentioned, which has been in our backlog for a while now.

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99, we're consolidating the missing parts on our backend before being able to roll out the US aggregation.
> We are going to combine and clean some of the US you mentioned, which has been in our backlog for a while now.

Sounds like a plan, I'll just leave them as is for now then and we can make the necessary changes when the backend work is done.

**Comment by VIKTORVAV99** [comment]
Closed in favour of #4741.

**Pull request closed without merging**
