### PR TITLE
Fix bad French values

### PR DESCRIPTION
**Pull request by nathantau**
## Issue
https://github.com/electricitymaps/electricitymaps-contrib/issues/4845

## Description

The goal of this PR is to replace the bad values observed in issue https://github.com/electricitymaps/electricitymaps-contrib/issues/4845 with proper values for the French version.

In the snapshot, the text is now 'représentant X% des émissions de CO2' instead of previously 'représentation X% d'émissions de CO2'.

### Preview

image

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Since this is a grammar change it should be pretty straight forward so this look good to me! 🎉

Thanks for making the PR.

**Comment by VIKTORVAV99** [comment]
I can't seem to update this branch (and I can't merge it without updating it) so perhaps you can update it with the latest changes from our master branch?

**Comment by meiyiniu** [comment]
@VIKTORVAV99, I just updated it - can you try merging it now?

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99, I just updated it - can you try merging it now?

Done! 🎉

Congrats on getting the PR merged!

**Pull request merged**
