### PR TITLE
Implement `fetch_exchange` in HN.py

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Issue
Delayed exchange between Honduras and Nicaragua.
## Description
I hadn't planned on implementing this so soon but I was just looking to see if the production parser was working as expected and I noticed that the exchange between Honduras (HN) and Nicaragua (NI) was very delayed.

So I implemented a `fetch_exchange` function to get the data from the same source as the HN production data. This also gives us the benefit of getting the data for the whole day (not the last 24 hours) compared to hourly in the parser we use today (ENTE).

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@madsnedergaard can we turn of the Netlify previews now that we got the ones Cloudflare? To have both seem a little excessive. 😅

**Comment by madsnedergaard** [comment]
> @madsnedergaard can we turn off the Netlify previews now that we got the ones from Cloudflare? To have both seem a little excessive. 😅

We actually ended up going the opposite direction and disabling Cloudflare previews, as we cannot adjust it to only create/share preview builds if there are frontend changes. Netlify supports that, so for now we'll stick with them and live with having different platforms :)

**Comment by mathilde-daugy** [comment]
Looks good, I have a few comments regarding overall readability. I think a bit of refactoring would make this a bit more streamlined. :)

**Comment by VIKTORVAV99** [comment]
> Looks good, I have a few comments regarding overall readability. I think a bit of refactoring would make this a bit more streamlined. :)

Hehe Pierre said the same thing last time 😅
But I can't seem to see any other comments? Are you sure they where submitted correctly?

**Comment by mathilde-daugy** [comment]
> > Looks good, I have a few comments regarding overall readability. I think a bit of refactoring would make this a bit more streamlined. :)
> 
> Hehe Pierre said the same thing last time 😅 But I can't seem to see any other comments? Are you sure they where submitted correctly?

Turns out I didn't submit the review 😅

**Comment by VIKTORVAV99** [comment]
> > > Looks good, I have a few comments regarding overall readability. I think a bit of refactoring would make this a bit more streamlined. :)
> > 
> > 
> > Hehe Pierre said the same thing last time 😅 But I can't seem to see any other comments? Are you sure they where submitted correctly?
> 
> Turns out I didn't submit the review 😅

I'll take a look at them and see what I can do!

**Comment by VIKTORVAV99** [comment]
@mathilde-daugy I refactored things a little, not sure if this is what you had in mind or if it's easier to read but there should be less code duplication at least.

**Comment by mathilde-daugy** [comment]
Thanks for refarctoring @VIKTORVAV99, it looks much better :) 
Just one small conflict to resolve and then we can merge.

**Comment by VIKTORVAV99** [comment]
> Thanks for refarctoring @VIKTORVAV99, it looks much better :) Just one small conflict to resolve and then we can merge.

I'll take care of it!

@madsnedergaard we really need to get #5082 merged... 😅

**Review by mathilde-daugy — APPROVED** [review]

**Pull request merged**
