### PR TITLE
Removed zone-list.scss & moved some other CSS to styled components

### PR DESCRIPTION
**Pull request by hboisgibault**
- Removed unused classes from CSS (#left-panel-highscore-back, #footer, .country-spot-price...)
- Migrated CSS to styled components for CircularGauge, ColorBlindCheckbox, ZoneList, EmissionRect, MapCountryTooltip
- Removed _zone-list.scss in consequence and CSS files size is reduced
- Added global CSS variables for colors, to be used in styled components

In accordance to #2261 to get rid of CSS files

### CODE REVIEW

**Comment by Kongkille** [comment]
Thanks for opening this PR @hboisgibault, this is super nice. 

Sorry for the delayed review, we'll get it in soon!

**Comment by madsnedergaard** [comment]
Thanks for updating and sorry for the slow response on our side, I'll review it today! :)

**Comment by madsnedergaard** [comment]
Thanks for the work here! I'll rebase and fix some conflicts/repeated work, so you should not continue working on this branch any more 😄

**Comment by hboisgibault** [comment]
Hi @madsnedergaard, thanks for the review !
Sure I will stop working on the branch. Tell me some changes are needed :)

**Review by madsnedergaard — APPROVED** [review]
Rebased and tested, LGTM! 👌

**Comment by madsnedergaard** [comment]
As you saw in #4731, we're going to refactor the app substantially. While the work here is great (and thanks for doing it! 🙏), we should probably wait with rewriting more of the Sass code as we're about to begin working on the new project :)

**Pull request merged**
