### PR TITLE
WIP: Adds new workflow for running Lighthouse

### PR DESCRIPTION
**Pull request by madsnedergaard**
Just testing if this is feasible and worth it :)

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Lighthouse actually have their on CI action we could potentially use at https://github.com/GoogleChrome/lighthouse-ci, I've used it in a personal project once and it worked pretty good.

**Comment by madsnedergaard** [comment]
Ah cool, missed that one 😅
It does seem like it requires managing/setting up more infrastructure compared to the unofficial action used here - is that correct? Anyway, it didn't work out of the box and I was a bit unsure if it's nice or just a bit noisy as most PRs will not affect the score. So maybe we should just run a test manually if it matters instead? 😅

**Comment by VIKTORVAV99** [comment]
> Ah cool, missed that one 😅 It does seem like it requires managing/setting up more infrastructure compared to the unofficial action used here - is that correct? Anyway, it didn't work out of the box and I was a bit unsure if it's nice or just a bit noisy as most PRs will not affect the score. So maybe we should just run a test manually if it matters instead? 😅

No not really, that is only for historical comparisons and long term trends but you can definitely run it without it and just use the public temporary storage.

I have been running all the PR's affecting the build systems manually already but it would be nice to have some sort of automated system that is consistent across PR's/environments so we aren't just measuring local performance.(The new preview builds help with that.)

**Comment by madsnedergaard** [comment]
Yeah that would be nice. Can't remember where I documented this idea (probably one of my multiple personal note-taking apps), so sharing it here for you too: I think it would be nice to have a bunch of "checks" (LH score, test coverage, type coverage, etc.) that validate that we are not decreasing any of those numbers. So it would only post a comment if there was a problem ("X is now lower than it was is on `master`"), instead of spamming every PR that might be unrelated with the values :)

**Comment by VIKTORVAV99** [comment]
> Yeah that would be nice. Can't remember where I documented this idea (probably one of my multiple personal note-taking apps), so sharing it here for you too: I think it would be nice to have a bunch of "checks" (LH score, test coverage, type coverage, etc.) that validate that we are not decreasing any of those numbers. So it would only post a comment if there was a problem ("X is now lower than it was is on `master`"), instead of spamming every PR that might be unrelated with the values :)

You did put some of these ideas as draft issues in the project 😅
But yes it would be nice to have a robust regression test suit, GitHub has some nice features for putting it in a summary field in the CI tab we can explore as well, like how the Cypress action does it.

**Pull request closed without merging**
