### PR TITLE
feat(web): Record language selection in Plausible

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
We don't know much about our users preferred languages

## Description
This PR posts an event to Plausible when a language is selected.

I've also created the following events in Plausible:
- Custom goal `Language Selected`
- Custom property `language`

### CODE REVIEW

**Comment by silkeholmebonnen** [comment]
Just checked in plausible and I cannot see a goal called `Language Selected`. I should be able to see it under `site settings` -> `goals`, right? Or am I looking at the wrong place

**Comment by tonypls** [comment]
> Just checked in plausible and I cannot see a goal called `Language Selected`. I should be able to see it under `site settings` -> `goals`, right? Or am I looking at the wrong place

It should be there, make sure you're looking at the app.electricitymaps.com page. Another way to test it is to visit this branch preview on a browser without ad blocker (I just use incognito mode) and change the language, then see if it's present as an event.

**Comment by silkeholmebonnen** [comment]
Ahh I was looking at electricitymaps.com page. How can i add app.electricitymaps.com so I can see it in Plausible?

**Comment by tonypls** [comment]
> Ahh I was looking at electricitymaps.com page. How can i add app.electricitymaps.com so I can see it in Plausible?

I've invited you

**Pull request merged**
