### PR TITLE
Upgrade GCCIA parser to Event datastructure.

### PR DESCRIPTION
**Pull request by unitrium**
## Issue

As part of the upgrade of our parsers to the Event datastructure, upgrade the GCCIA parser to the Event datastructure.

## Description

- Fetch Consumption uses now ConsumptionList datastructure.

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Nice changes!
SA don't seem to work though, is there anything we can do to fix that?

**Comment by unitrium** [comment]
You mean on the map ? Or the website?

**Comment by VIKTORVAV99** [comment]
> You mean on the map ? Or the website?

The consumption parser for SA, but perhaps it just don't have any data?

**Comment by q--** [comment]
I'm not sure if it's ever worked. SA was one of the countries that did display `-` instead of consumption on the map on the GCCIA website when I added it.

**Comment by VIKTORVAV99** [comment]
> I'm not sure if it's ever worked. SA was one of the countries that did display `-` instead of consumption on the map on the GCCIA website when I added it.

If that's the case there isn't much we can do about it. Thanks for the confirmation.

**Pull request merged**
